import { useCommunityResource } from '../../hooks/useCommunityResource';
import { communityService } from '../../services/communityService';
import { Paperclip, Send, X } from 'lucide-react';
import { useRef, useState, type KeyboardEvent } from 'react';
import Button from '../common/Button';
import type { CommunityMessage } from '../../types/community';

export default function ChatComposer({ locked, busy, replyTo, cancelReply, send }: { locked: boolean; busy: boolean; replyTo: CommunityMessage | null; cancelReply: () => void; send: (content: string, files: File[]) => Promise<boolean> }) {
  const policy = useCommunityResource('upload-policy', communityService.getUploadPolicy, 60000);
  const [error, setError] = useState('');
  const choose = (next: File[]) => { const p = policy.data; if (!p) { setError('Upload settings are unavailable. Please retry.'); return; } if (next.length > p.maxFiles || next.some(f => !f.size || f.size > p.maxBytes || !p.mimeTypes.includes(f.type) || !p.extensions.includes(f.name.split('.').pop()?.toLowerCase() ?? ''))) { setError(`Choose up to ${p.maxFiles} supported files, each no larger than ${Math.floor(p.maxBytes / 1024 / 1024)} MB.`); return; } setError(''); setFiles(next); };
  const [content, setContent] = useState(''); const [files, setFiles] = useState<File[]>([]); const input = useRef<HTMLTextAreaElement>(null);
  const submit = async () => { if (!content.trim() || busy || locked) return; if (content.trim().length > 10000) { setError('Keep the message under 10,000 characters.'); return; } if (await send(content.trim(), files)) { setContent(''); setFiles([]); setError(''); input.current?.focus(); } };
  const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit(); } };
  return <div className="border-t border-paper-border bg-paper-raised p-3">{replyTo && <div className="mb-2 flex items-center justify-between rounded-md bg-forum-50 p-2 text-xs text-ink-muted"><span className="truncate">Replying to <strong>{replyTo.senderName}</strong>: {replyTo.content}</span><button type="button" aria-label="Cancel reply" onClick={cancelReply}><X className="h-4 w-4" /></button></div>}{locked ? <p className="rounded-md bg-warning-50 p-3 text-center text-sm text-warning-700">This conversation is locked.</p> : <><textarea disabled={busy} maxLength={10000} ref={input} aria-label="Message" rows={3} value={content} onChange={(e) => setContent(e.target.value)} onKeyDown={keyDown} placeholder="Write a message…" className="w-full resize-none rounded-md border border-paper-border p-3 text-sm focus:border-forum-600 focus:outline-none focus:ring-2 focus:ring-forum-600/20" />{(error || policy.error) && <p role="alert" className="mt-1 text-xs text-danger-600">{error || policy.error}</p>}{files.length > 0 && <p className="mt-1 truncate text-xs text-ink-muted">{files.map((file) => file.name).join(', ')}</p>}<div className="mt-2 flex items-center justify-between"><label title="Attach files" className="cursor-pointer rounded-md p-2 text-ink-muted hover:bg-forum-50"><Paperclip className="h-4 w-4" /><input disabled={busy || !policy.data} accept={policy.data?.extensions.map(ext => `.${ext}`).join(',')} type="file" multiple className="sr-only" onChange={(e) => choose(Array.from(e.target.files ?? []))} /></label><Button size="sm" disabled={busy || !content.trim()} onClick={() => void submit()}>{busy ? 'Sending…' : 'Send'}<Send className="h-4 w-4" /></Button></div></>}</div>;
}
