import { CommunityAttachmentLink } from './CommunityMedia';
import { Eye, EyeOff, Mail, MailOpen, Pin, PinOff, Reply, Trash2 } from 'lucide-react';
import Badge from '../common/Badge';
import type { CommunityMessage } from '../../types/community';
import CommunityAvatar from './CommunityAvatar';
import { formatDate } from './AdminCommunityUi';

export default function ChatMessageItem({ message, onReply, onPatch, onDelete, disabled }: { message: CommunityMessage; onReply: () => void; onPatch: (patch: { isPinned?: boolean; isHidden?: boolean; isRead?: boolean }) => void; onDelete: () => void; disabled?: boolean }) {
  return <article className={`group rounded-lg border p-3 ${message.senderRole === 'ADMIN' ? 'border-brass-200 bg-brass-50/40' : 'border-paper-border bg-paper-raised'}`}><div className="flex gap-3"><CommunityAvatar name={message.senderName} src={message.senderImageUrl} className="rounded-full" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-forum-900">{message.senderName}</span><Badge variant={message.senderRole === 'ADMIN' ? 'brass' : 'default'}>{message.senderRole}</Badge>{message.isPinned && <span title="Pinned"><Pin className="h-3.5 w-3.5 text-brass-700" /></span>}<time className="ml-auto text-xs text-ink-subtle">{formatDate(message.createdAt)}</time></div>{message.replyTo && <div className="mt-2 border-l-2 border-forum-200 pl-3 text-xs text-ink-muted"><span className="font-medium">{message.replyTo.senderName}</span>: {message.replyTo.content}</div>}<p className={`mt-2 whitespace-pre-wrap break-words text-sm ${message.isDeleted || message.isHidden ? 'italic text-ink-subtle' : 'text-forum-900'}`}>{message.isDeleted ? 'This message was deleted.' : message.isHidden ? 'This message is hidden.' : message.content}</p>{!message.isDeleted && message.attachments?.length ? <div className="mt-2 flex flex-wrap gap-2">{message.attachments.map((file) => <CommunityAttachmentLink key={file.id} file={file} className="rounded-md border border-paper-border px-2 py-1 text-xs text-forum-700 hover:bg-forum-50" />)}</div> : null}<div className="mt-2 flex flex-wrap gap-1 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 sm:group-focus-within:opacity-100"><Action title="Reply" disabled={disabled || message.isDeleted} onClick={onReply}><Reply /></Action><Action title={message.isPinned ? 'Unpin' : 'Pin'} disabled={disabled || message.isDeleted} onClick={() => onPatch({ isPinned: !message.isPinned })}>{message.isPinned ? <PinOff /> : <Pin />}</Action><Action title={message.isRead === false ? 'Mark read' : 'Mark unread'} disabled={disabled || message.isDeleted} onClick={() => onPatch({ isRead: message.isRead === false })}>{message.isRead === false ? <MailOpen /> : <Mail />}</Action><Action title={message.isHidden ? 'Restore' : 'Hide'} disabled={disabled || message.isDeleted} onClick={() => onPatch({ isHidden: !message.isHidden })}>{message.isHidden ? <Eye /> : <EyeOff />}</Action><Action title="Delete" danger disabled={disabled || message.isDeleted} onClick={onDelete}><Trash2 /></Action></div></div></div></article>;
}
function Action({ title, children, onClick, disabled, danger = false }: { title: string; children: React.ReactNode; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button type="button" title={title} aria-label={title} disabled={disabled} onClick={onClick} className={`rounded p-1.5 disabled:opacity-30 ${danger ? 'text-danger-600 hover:bg-danger-50' : 'text-ink-muted hover:bg-forum-50'} [&>svg]:h-4 [&>svg]:w-4`}>{children}</button>; }
