import { Paperclip, Send, X } from 'lucide-react';
import { useRef, useState, type KeyboardEvent } from 'react';
import Button from '../common/Button';
import type { CommunityMessage } from '../../types/community';

export default function ChatComposer({ locked, busy, replyTo, cancelReply, send }: { locked: boolean; busy: boolean; replyTo: CommunityMessage | null; cancelReply: () => void; send: (content: string, files: File[]) => Promise<boolean> }) {
  const [content, setContent] = useState(''); const [files, setFiles] = useState<File[]>([]); const input = useRef<HTMLTextAreaElement>(null);
  const submit = async () => { if (!content.trim() || busy || locked) return; if (await send(content.trim(), files)) { setContent(''); setFiles([]); input.current?.focus(); } };
  const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit(); } };
  return <div className="border-t border-paper-border bg-paper-raised p-3">{replyTo && <div className="mb-2 flex items-center justify-between rounded-md bg-forum-50 p-2 text-xs text-ink-muted"><span className="truncate">Replying to <strong>{replyTo.senderName}</strong>: {replyTo.content}</span><button type="button" aria-label="Cancel reply" onClick={cancelReply}><X className="h-4 w-4" /></button></div>}{locked ? <p className="rounded-md bg-warning-50 p-3 text-center text-sm text-warning-700">This conversation is locked.</p> : <><textarea ref={input} aria-label="Message" rows={3} value={content} onChange={(e) => setContent(e.target.value)} onKeyDown={keyDown} placeholder="Write a message…" className="w-full resize-none rounded-md border border-paper-border p-3 text-sm focus:border-forum-600 focus:outline-none focus:ring-2 focus:ring-forum-600/20" />{files.length > 0 && <p className="mt-1 truncate text-xs text-ink-muted">{files.map((file) => file.name).join(', ')}</p>}<div className="mt-2 flex items-center justify-between"><label title="Attach files" className="cursor-pointer rounded-md p-2 text-ink-muted hover:bg-forum-50"><Paperclip className="h-4 w-4" /><input type="file" multiple className="sr-only" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /></label><Button size="sm" disabled={busy || !content.trim()} onClick={() => void submit()}>{busy ? 'Sending…' : 'Send'}<Send className="h-4 w-4" /></Button></div></>}</div>;
}
