import { CommunityImage } from './CommunityMedia';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Button from '../common/Button';
import { SelectInput, TextArea, TextInput } from '../common/Input';
import { ExchangeModal } from '../exchange/ExchangeDialog';
import type { Community, CommunityPayload, CommunityStatus, CommunityVisibility } from '../../types/community';

const MAX_IMAGE = 5 * 1024 * 1024;
const IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export default function CommunityFormModal({ community, busy, onClose, onSubmit, serverErrors }: { community?: Community; busy: boolean; onClose: () => void; onSubmit: (payload: CommunityPayload) => Promise<void>; serverErrors?: Record<string, string> }) {
  const [form, setForm] = useState({ name: community?.name ?? '', slug: community?.slug ?? '', description: community?.description ?? '', category: community?.category ?? '', visibility: community?.visibility ?? 'PUBLIC' as CommunityVisibility, status: community?.status ?? 'ACTIVE' as CommunityStatus });
  const [files, setFiles] = useState<{ image?: File; banner?: File }>({});
  const [previews, setPreviews] = useState<{ image?: string; banner?: string }>({ image: community?.imageUrl, banner: community?.bannerUrl });
  const [errors, setErrors] = useState<Record<string, string>>({});
  useEffect(() => { if (serverErrors) setErrors(serverErrors); }, [serverErrors]);
  const [slugEdited, setSlugEdited] = useState(Boolean(community));
  const previewUrls = useRef<{ image?: string; banner?: string }>({});
  useEffect(() => { const urls = previewUrls.current; return () => Object.values(urls).forEach(url => { if (url) URL.revokeObjectURL(url); }); }, []);
  const change = (key: keyof typeof form, value: string) => { setForm((current) => ({ ...current, [key]: value, ...(key === 'name' && !slugEdited ? { slug: slugify(value) } : {}) })); setErrors((current) => ({ ...current, [key]: '' })); };
  const choose = (key: 'image' | 'banner', file?: File) => { if (!file) return; if (!IMAGE_TYPES.includes(file.type)) { setErrors((e) => ({ ...e, [key]: 'Choose a JPG, PNG, or WebP image.' })); return; } if (file.size > MAX_IMAGE) { setErrors((e) => ({ ...e, [key]: 'Image must be 5 MB or smaller.' })); return; } setFiles((f) => ({ ...f, [key]: file })); const previous = previewUrls.current[key]; if (previous) URL.revokeObjectURL(previous); const url = URL.createObjectURL(file); previewUrls.current[key] = url; setPreviews((p) => ({ ...p, [key]: url })); setErrors((e) => ({ ...e, [key]: '' })); };
  const submit = (event: FormEvent) => { event.preventDefault(); const next: Record<string, string> = {}; if (!form.name.trim()) next.name = 'Community name is required.'; if (!form.slug.trim()) next.slug = 'Slug is required.'; else if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)) next.slug = 'Use lowercase letters, numbers, and hyphens.'; if (!form.description.trim()) next.description = 'Description is required.'; if (!form.category.trim()) next.category = 'Category is required.'; setErrors(next); if (Object.keys(next).length) return; void onSubmit({ ...form, image: files.image, banner: files.banner }); };
  return <ExchangeModal title={community ? 'Edit community' : 'Add community'} close={onClose} busy={busy} wide><form onSubmit={submit} className="space-y-4"><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><TextInput required label="Community name" value={form.name} error={errors.name} onChange={(e) => change('name', e.target.value)} /><TextInput required label="Slug" value={form.slug} error={errors.slug} onChange={(e) => { setSlugEdited(true); change('slug', slugify(e.target.value)); }} /><TextInput required label="Category" value={form.category} error={errors.category} onChange={(e) => change('category', e.target.value)} /><SelectInput label="Visibility" value={form.visibility} onChange={(e) => change('visibility', e.target.value)}><option value="PUBLIC">Public</option><option value="PRIVATE">Private</option></SelectInput><SelectInput label="Status" value={form.status} onChange={(e) => change('status', e.target.value)}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ARCHIVED">Archived</option></SelectInput><div /><TextArea required className="sm:col-span-2" label="Description" value={form.description} error={errors.description} onChange={(e) => change('description', e.target.value)} /><ImageField label="Profile image" error={errors.image} preview={previews.image} onChange={(file) => choose('image', file)} /><ImageField label="Banner image" error={errors.banner} preview={previews.banner} onChange={(file) => choose('banner', file)} /></fieldset><div className="flex justify-end gap-2 border-t border-paper-border pt-4"><Button type="button" variant="ghost" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : community ? 'Save changes' : 'Create community'}</Button></div></form></ExchangeModal>;
}

function ImageField({ label, preview, error, onChange }: { label: string; preview?: string; error?: string; onChange: (file?: File) => void }) {
  return <label className="block text-sm font-medium text-forum-900">{label}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => onChange(e.target.files?.[0])} className="mt-1 block w-full text-sm" />{preview && <CommunityImage src={preview} alt={`${label} preview`} className="mt-2 h-24 w-full rounded-md object-cover" />}{error ? <span className="mt-1 block text-xs text-danger-600">{error}</span> : <span className="mt-1 block text-xs text-ink-muted">JPG, PNG, or WebP up to 5 MB.</span>}</label>;
}
