import Button from '../common/Button';
import { CommunityAttachmentLink } from './CommunityMedia';
import type { CommunityReport } from '../../types/community';
import CommunityStatusBadge from './CommunityStatusBadge';
import { Drawer, formatDate } from './AdminCommunityUi';

export default function CommunityReportDetailsDrawer({ report, close, error, retry }: { report: CommunityReport; close: () => void; error?: string | null; retry?: () => void }) {
  return <Drawer title="Report details" close={close}>{error && <div role="alert" className="mb-4 rounded-lg bg-warning-50 p-3 text-sm text-warning-700"><p>{error}</p><Button variant="outline" onClick={retry}>Retry report refresh</Button></div>}<div className="flex items-center justify-between gap-3"><div><p className="text-sm text-ink-muted">Report {report.id}</p><h3 className="mt-1 text-lg font-semibold text-forum-900">{report.reason}</h3></div><CommunityStatusBadge status={report.status} /></div><dl className="mt-6 grid grid-cols-2 gap-5 text-sm"><Item label="Community" value={report.communityName} /><Item label="Reported" value={formatDate(report.createdAt)} /><Item label="Reporter" value={report.reporterName} /><Item label="Reported member" value={report.reportedMemberName ?? '—'} /><Item label="Assigned admin" value={report.assignedAdminName ?? 'Unassigned'} /></dl><section className="mt-6 rounded-lg border border-paper-border p-4" aria-label="Original evidence"><h4 className="font-semibold text-forum-900">Original evidence</h4>{report.evidence ? <>
      <p className="mt-2 text-xs text-ink-muted">Captured {formatDate(report.evidence.capturedAt)}</p>
      {report.evidence.message && <><p className="mt-2 text-sm">{report.evidence.message.author.fullName} · {report.evidence.message.conversation.title}{report.evidence.message.replyToId ? ' · Reply' : ''} · {formatDate(report.evidence.message.createdAt)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{report.evidence.message.content}</p></>}
      {report.evidence.member && <p className="mt-2 text-sm">{report.evidence.member.user.fullName} · {report.evidence.member.role} · {report.evidence.member.status}</p>}
      {report.evidence.attachments.map(file => <CommunityAttachmentLink key={file.id} file={{ ...file, fileUrl: `/admin/community/reports/${report.id}/evidence/${file.id}` }} className="mt-2 block break-words text-xs text-forum-700 underline" />)}
    </> : <p className="mt-2 text-sm text-ink-muted">Original evidence unavailable. This report predates evidence capture.</p>}</section>{report.reportedMessage && <section className="mt-6 rounded-lg border border-paper-border bg-forum-50 p-4"><p className="text-xs uppercase tracking-wide text-ink-subtle">Current content{report.reportedMessage.isHidden ? ' · Hidden' : ''}{report.reportedMessage.isDeleted ? ' · Deleted' : ''}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-forum-900">{report.reportedMessage.isDeleted ? 'This message was deleted.' : report.reportedMessage.content}</p>{!report.reportedMessage.isDeleted && report.reportedMessage.attachments?.map(file => <CommunityAttachmentLink key={file.id} file={file} className="mt-2 block break-words text-xs text-forum-700 underline" />)}</section>}<Section title="Current membership" value={report.reportedMemberName ? report.targetMemberState ?? 'Unavailable' : 'Unavailable'} /><Section title="Reporter notes" value={report.notes} /><Section title="Resolution notes" value={report.resolutionNotes} /><section className="mt-6"><h4 className="font-semibold text-forum-900">Moderation action history</h4><div className="mt-3 space-y-3">{report.actionHistory?.length ? report.actionHistory.map((item) => <div key={item.id} className="border-l-2 border-brass-500 pl-3 text-sm"><p className="font-medium text-forum-900">{item.action}</p><p className="text-ink-muted">{item.notes}</p><p className="mt-1 text-xs text-ink-subtle">{item.adminName ?? 'Administrator'} · {formatDate(item.createdAt)}</p></div>) : <p className="text-sm text-ink-muted">No moderation actions recorded.</p>}</div></section></Drawer>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wide text-ink-subtle">{label}</dt><dd className="mt-1 text-forum-900">{value}</dd></div>; }
function Section({ title, value }: { title: string; value?: string }) { return <section className="mt-6"><h4 className="font-semibold text-forum-900">{title}</h4><p className="mt-2 whitespace-pre-wrap text-sm text-ink-muted">{value || 'None provided.'}</p></section>; }
