import { CommunityAttachmentLink } from './CommunityMedia';
import type { CommunityReport } from '../../types/community';
import CommunityStatusBadge from './CommunityStatusBadge';
import { Drawer, formatDate } from './AdminCommunityUi';

export default function CommunityReportDetailsDrawer({ report, close }: { report: CommunityReport; close: () => void }) {
  return <Drawer title="Report details" close={close}><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-ink-muted">Report {report.id}</p><h3 className="mt-1 text-lg font-semibold text-forum-900">{report.reason}</h3></div><CommunityStatusBadge status={report.status} /></div><dl className="mt-6 grid grid-cols-2 gap-5 text-sm"><Item label="Community" value={report.communityName} /><Item label="Reported" value={formatDate(report.createdAt)} /><Item label="Reporter" value={report.reporterName} /><Item label="Reported member" value={report.reportedMemberName ?? '—'} /><Item label="Assigned admin" value={report.assignedAdminName ?? 'Unassigned'} /></dl>{report.reportedMessage && <section className="mt-6 rounded-lg border border-paper-border bg-forum-50 p-4"><p className="text-xs uppercase tracking-wide text-ink-subtle">Reported content</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-forum-900">{report.reportedMessage.isDeleted ? 'This message was deleted.' : report.reportedMessage.content}</p>{!report.reportedMessage.isDeleted && report.reportedMessage.attachments?.map(file => <CommunityAttachmentLink key={file.id} file={file} className="mt-2 block break-words text-xs text-forum-700 underline" />)}</section>}<Section title="Reporter notes" value={report.notes} /><Section title="Resolution notes" value={report.resolutionNotes} /><section className="mt-6"><h4 className="font-semibold text-forum-900">Moderation action history</h4><div className="mt-3 space-y-3">{report.actionHistory?.length ? report.actionHistory.map((item) => <div key={item.id} className="border-l-2 border-brass-500 pl-3 text-sm"><p className="font-medium text-forum-900">{item.action}</p><p className="text-ink-muted">{item.notes}</p><p className="mt-1 text-xs text-ink-subtle">{item.adminName ?? 'Administrator'} · {formatDate(item.createdAt)}</p></div>) : <p className="text-sm text-ink-muted">No moderation actions recorded.</p>}</div></section></Drawer>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wide text-ink-subtle">{label}</dt><dd className="mt-1 text-forum-900">{value}</dd></div>; }
function Section({ title, value }: { title: string; value?: string }) { return <section className="mt-6"><h4 className="font-semibold text-forum-900">{title}</h4><p className="mt-2 whitespace-pre-wrap text-sm text-ink-muted">{value || 'None provided.'}</p></section>; }
