import { Router } from 'express';
import { z } from 'zod';
import rateLimit from 'express-rate-limit';
import { requireAuth, requireRole, requireVerifiedSession } from '../middleware/auth';
import { validate } from '../middleware/validate';
import { asyncHandler } from '../utils/asyncHandler';
import { securityAudit } from '../services/audit.service';
import { sendFailure, sendSuccess } from '../utils/apiResponse';
import { passwordBody, updateProfileBody } from '../domain/admin-profile';
import * as service from '../services/admin-profile.service';
import { avatarUpload, replaceAvatar, streamAvatar } from '../services/admin-avatar.service';
const router = Router();
router.use(requireAuth, requireRole('ADMIN'), requireVerifiedSession);
router.use((_req, res, next) => { res.setHeader('Cache-Control', 'private, no-store'); next(); });
router.get('/', asyncHandler(async (req, res) => sendSuccess(res, await service.getProfile(req.user!.id))));
router.patch('/', validate({ body: updateProfileBody }), asyncHandler(async (req, res) => sendSuccess(res, await service.updateProfile(req.user!.id, req.body), 'Changes saved.')));
router.get('/overview', asyncHandler(async (req, res) => sendSuccess(res, await service.overview(req.user!.id))));
router.get('/avatar', streamAvatar);
router.post('/avatar', avatarUpload, validate({ body: z.object({ expectedRevision: z.coerce.number().int().min(0) }).strict() }), asyncHandler(async (req, res) => sendSuccess(res, await replaceAvatar(req.user!.id, req.body.expectedRevision, req.file), 'Avatar updated.')));
router.post('/password', rateLimit({ windowMs: 15 * 60000, max: 10, keyGenerator: req => req.user!.id, handler: async (req, res) => { await securityAudit({ actorId: req.user!.id, action: 'AuthenticationThrottled', entity: `User ${req.user!.id}`, outcome: 'DENIED' }); sendFailure(res, 429, 'Too many password-change attempts. Try again in 15 minutes.'); } }), validate({ body: passwordBody }), asyncHandler(async (req, res) => sendSuccess(res, await service.changePassword(req.user!.id, req.user!.sessionId!, req.body), 'Password updated. Other sessions have been signed out.')));
router.get('/sessions', asyncHandler(async (req, res) => sendSuccess(res, await service.sessions(req.user!.id, req.user!.sessionId!, req.query))));
router.delete('/sessions/:id', asyncHandler(async (req, res) => sendSuccess(res, await service.revokeSessions(req.user!.id, req.user!.sessionId!, req.params.id))));
router.post('/sessions/revoke-others', asyncHandler(async (req, res) => sendSuccess(res, await service.revokeSessions(req.user!.id, req.user!.sessionId!))));
export default router;
