import fs from 'node:fs';
import { assertSafePath } from '../utils/fileStorage';
import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { requireAuth, requireRole } from '../middleware/auth';
import { asyncHandler } from '../utils/asyncHandler';
import { sendSuccess } from '../utils/apiResponse';
import { ApiError } from '../utils/ApiError';
import * as community from '../services/community.service';
import * as chat from '../services/community-chat.service';
import * as moderation from '../services/community-moderation.service';
import { assertAdmin, capabilities } from '../services/community-access.service';
import { communityUpload, uploaded, uploadPolicy } from '../services/community-upload.service';

const member = Router();
export const communityAdminRoutes = Router();
for (const router of [member, communityAdminRoutes]) router.use(requireAuth, requireRole('MEMBER'));
communityAdminRoutes.use(asyncHandler(async (req, _res, next) => { if (!(await capabilities(req.user!)).canModerate) throw ApiError.forbidden(); next(); }));
const endpoint = (fn: (req: Request, res: Response) => Promise<unknown>, status = 200) => asyncHandler(async (req, res) => { sendSuccess(res, await fn(req, res), 'Community request completed', status); });
const adminOnly = asyncHandler(async (req, _res, next) => { assertAdmin(req.user!); next(); });
const sent = (res: Response, value: unknown) => { res.locals.communityUploadCommitted = true; return value; };
member.get('/capabilities', endpoint(req => capabilities(req.user!)));
member.get('/upload-policy', endpoint(async () => uploadPolicy));
member.get('/options', endpoint(req => community.options(req.user!)));
member.get('/communities/mine', endpoint(req => community.communities(req.user!, req.query, false, true)));
member.get('/communities', endpoint(req => community.communities(req.user!, req.query)));
member.get('/communities/:id', endpoint(req => community.communityDetail(req.user!, req.params.id!)));
member.post('/communities/:id/join', endpoint(req => community.membershipAction(req.user!, req.params.id!, 'join')));
member.delete('/communities/:id/join-request', endpoint(req => community.membershipAction(req.user!, req.params.id!, 'cancel')));
member.delete('/communities/:id/membership', endpoint(req => community.membershipAction(req.user!, req.params.id!, 'leave')));
member.get('/communities/:id/members', endpoint(req => community.members(req.user!, req.query, req.params.id!)));
member.get('/communities/:id/conversations', endpoint(req => chat.conversations(req.user!, req.query, false, req.params.id!)));
member.get('/conversations/:id/messages', endpoint(req => chat.messages(req.user!, req.params.id!, req.query)));
member.post('/conversations/:id/messages', communityUpload('attachments'), endpoint(async (req, res) => sent(res, await chat.send(req.user!, req.params.id!, req.body, uploaded(req))), 201));
member.patch('/messages/:id', endpoint(req => chat.changeMessage(req.user!, req.params.id!, req.body)));
member.delete('/messages/:id', endpoint(req => chat.changeMessage(req.user!, req.params.id!, {}, false, true)));
member.post('/messages/:id/report', endpoint(req => moderation.createReport(req.user!, req.params.id!, req.body, 'message'), 201));
member.post('/members/:id/report', endpoint(req => moderation.createReport(req.user!, req.params.id!, req.body, 'member'), 201));
communityAdminRoutes.get('/options', endpoint(req => community.options(req.user!, true)));
communityAdminRoutes.get('/dashboard', adminOnly, endpoint(req => moderation.dashboard(req.user!)));
communityAdminRoutes.get('/communities', endpoint(req => community.communities(req.user!, req.query, true)));
communityAdminRoutes.get('/communities/:id', endpoint(req => community.communityDetail(req.user!, req.params.id!, true)));
communityAdminRoutes.post('/communities', adminOnly, communityUpload('images'), endpoint(async (req, res) => sent(res, await community.saveCommunity(req.user!, req.body, uploaded(req))), 201));
communityAdminRoutes.patch('/communities/:id', adminOnly, communityUpload('images'), endpoint(async (req, res) => sent(res, await community.saveCommunity(req.user!, req.body, uploaded(req), req.params.id!))));
communityAdminRoutes.patch('/communities/:id/status', adminOnly, endpoint(req => community.changeCommunity(req.user!, req.params.id!, z.object({ status: z.string() }).strict().parse(req.body).status)));
communityAdminRoutes.delete('/communities/:id', adminOnly, endpoint(req => community.changeCommunity(req.user!, req.params.id!)));
communityAdminRoutes.get('/members', endpoint(req => community.members(req.user!, req.query)));
communityAdminRoutes.get('/members/:id', endpoint(req => community.memberDetail(req.user!, req.params.id!)));
communityAdminRoutes.patch('/members/:id/status', endpoint(req => community.changeMember(req.user!, req.params.id!, req.body, 'status')));
communityAdminRoutes.patch('/members/:id/role', adminOnly, endpoint(req => community.changeMember(req.user!, req.params.id!, req.body, 'role')));
communityAdminRoutes.delete('/members/:id', endpoint(req => community.changeMember(req.user!, req.params.id!, req.body, 'remove')));
communityAdminRoutes.get('/conversations', endpoint(req => chat.conversations(req.user!, req.query, true)));
communityAdminRoutes.get('/conversations/:id/messages', endpoint(req => chat.messages(req.user!, req.params.id!, req.query, true)));
communityAdminRoutes.post('/conversations/:id/messages', communityUpload('attachments'), endpoint(async (req, res) => sent(res, await chat.send(req.user!, req.params.id!, req.body, uploaded(req), true)), 201));
communityAdminRoutes.patch('/conversations/:id', endpoint(req => chat.lockConversation(req.user!, req.params.id!, z.object({ isLocked: z.boolean() }).strict().parse(req.body).isLocked)));
communityAdminRoutes.patch('/messages/:id', endpoint(req => chat.changeMessage(req.user!, req.params.id!, req.body, true)));
communityAdminRoutes.delete('/messages/:id', endpoint(req => chat.changeMessage(req.user!, req.params.id!, {}, true, true)));
communityAdminRoutes.get('/reports', endpoint(req => moderation.reports(req.user!, req.query)));
communityAdminRoutes.get('/reports/:id/evidence/:attachmentId', asyncHandler(async (req, res) => {
  const file = await moderation.evidenceFile(req.user!, req.params.id!, req.params.attachmentId!);
  const path = assertSafePath(file.storageKey);
  await fs.promises.access(path, fs.constants.R_OK).catch(() => { throw ApiError.notFound('Evidence file not found'); });
  res.setHeader('Cache-Control', 'private, no-store');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
  res.setHeader('Content-Type', file.mimeType);
  res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(file.originalName)}`);
  const stream = fs.createReadStream(path);
  stream.on('error', () => res.destroy()); res.on('close', () => stream.destroy()); stream.pipe(res);
}));
communityAdminRoutes.get('/reports/:id', endpoint(req => moderation.reportDetail(req.user!, req.params.id!)));
communityAdminRoutes.patch('/reports/:id', endpoint(req => moderation.updateReport(req.user!, req.params.id!, req.body)));
communityAdminRoutes.post('/reports/:id/actions', endpoint(req => moderation.updateReport(req.user!, req.params.id!, req.body, true)));
export default member;
