import { Router } from 'express';
import { z } from 'zod';
import { requireAuth, requireRole, requireVerifiedSession } from '../middleware/auth';
import { validate } from '../middleware/validate';
import { asyncHandler } from '../utils/asyncHandler';
import { sendSuccess } from '../utils/apiResponse';
import { waiverReason } from '../domain/membership';
import { membershipDetail, reviewEvidence, changeCharge, restoreArchive } from '../services/membership-policy.service';
export const ownMembershipRoutes = Router();
export const adminMembershipRoutes = Router();
const requestId = z.string().uuid();
const waiver = z.object({ requestId, reason: waiverReason }).strict();
const params = z.object({ id: z.string().min(1), chargeId: z.string().min(1) });
const noStore: import('express').RequestHandler = (_req, res, next) => { res.setHeader('Cache-Control', 'private, no-store'); next(); };
ownMembershipRoutes.use(requireAuth, requireRole('APPLICANT', 'MEMBER'), requireVerifiedSession, noStore);
ownMembershipRoutes.get('/', asyncHandler(async (req, res) => sendSuccess(res, await membershipDetail(req.user!.id, req.user!.id))));
ownMembershipRoutes.post('/charges/:chargeId/waivers', validate({ body: waiver }), asyncHandler(async (req, res) => sendSuccess(res, await changeCharge(req.user!.id, req.params.chargeId!, req.user!.id, 'REQUEST_WAIVER', req.body, true))));
adminMembershipRoutes.use(requireAuth, requireRole('ADMIN'), requireVerifiedSession, noStore);
adminMembershipRoutes.get('/:id', asyncHandler(async (req, res) => sendSuccess(res, await membershipDetail(req.params.id!))));
adminMembershipRoutes.post('/:id/evidence-review', asyncHandler(async (req, res) => sendSuccess(res, await reviewEvidence(req.params.id!, req.user!.id))));
adminMembershipRoutes.post('/:id/charges/:chargeId/payments', validate({ params, body: z.object({ requestId, reference: z.string().trim().min(1).max(191) }).strict() }), asyncHandler(async (req, res) => sendSuccess(res, await changeCharge(req.params.id!, req.params.chargeId!, req.user!.id, 'PAY', req.body))));
adminMembershipRoutes.post('/:id/charges/:chargeId/corrections', validate({ params, body: z.object({ recordId: z.string().min(1), reason: waiverReason }).strict() }), asyncHandler(async (req, res) => sendSuccess(res, await changeCharge(req.params.id!, req.params.chargeId!, req.user!.id, 'REVERSE', req.body))));
adminMembershipRoutes.post('/:id/charges/:chargeId/waivers', validate({ params, body: waiver }), asyncHandler(async (req, res) => sendSuccess(res, await changeCharge(req.params.id!, req.params.chargeId!, req.user!.id, 'REQUEST_WAIVER', req.body))));
adminMembershipRoutes.post('/:id/charges/:chargeId/waiver-decision', validate({ params, body: z.object({ recordId: z.string().min(1), status: z.enum(['APPROVED', 'REJECTED', 'REVOKED']), reason: waiverReason }).strict() }), asyncHandler(async (req, res) => sendSuccess(res, await changeCharge(req.params.id!, req.params.chargeId!, req.user!.id, 'DECIDE_WAIVER', req.body))));
adminMembershipRoutes.post('/:id/restore', validate({ body: z.object({ enableAutoArchive: z.boolean().default(false) }).strict() }), asyncHandler(async (req, res) => sendSuccess(res, await restoreArchive(req.params.id!, req.user!.id, req.body.enableAutoArchive))));
