// Local end-to-end verification. Only this script's namespaced fixtures are removed.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
const { prisma } = require('../dist/config/database');
const { sha256, signAccessToken } = require('../dist/utils/security');
const { assertSafePath } = require('../dist/utils/fileStorage');
const base = process.env.EXCHANGE_API_URL || 'http://127.0.0.1:5003/api/v1';
const site = process.env.EXCHANGE_WEB_URL || 'http://127.0.0.1:5175';
const output = process.env.EXCHANGE_SCREENSHOT_DIR || '/private/tmp/document-exchange-browser';
const prefix = `exchange-browser-${crypto.randomUUID().slice(0, 8)}`;
const users = [], errors = [];
let browser, page;
async function actor(name, role) {
  const user = await prisma.user.create({ data: { fullName: `Exchange ${name}`, email: `${prefix}-${name}@example.test`, role, status: 'ACTIVE' } }); users.push(user.id);
  if (role === 'MEMBER') await prisma.memberProfile.create({ data: { userId: user.id, memberId: prefix, institution: 'Research Institute', professionalType: 'Scientist' } });
  const session = await prisma.session.create({ data: { userId: user.id, tokenHash: sha256(crypto.randomUUID()), expiresAt: new Date(Date.now() + 3600000) } });
  return { ...user, token: signAccessToken({ sub: user.id, sessionId: session.id, role }) };
}
async function screenshot(page, name) {
  await page.screenshot({ path: path.join(output, `${name}.png`), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}: horizontal overflow`);
  const dialog = page.getByRole('dialog');
  if (await dialog.count()) assert.ok(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth), `${name}: dialog overflow`);
}
async function api(actor, url, method = 'GET', body) {
  const response = await fetch(`${base}${url}`, { method, headers: { Authorization: `Bearer ${actor.token}`, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const result = await response.json(); assert.ok(response.ok, JSON.stringify(result)); return result.data;
}
async function context(actor) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addInitScript(token => localStorage.setItem('ifsmhp.accessToken', token), actor.token);
  const page = await context.newPage(); page.setDefaultTimeout(15000); page.on('pageerror', e => errors.push(e.message));
  return page;
}
(async () => {
  try {
    await fs.mkdir(output, { recursive: true });
    const member = await actor('Member', 'MEMBER'), admin = await actor('Administrator', 'ADMIN');
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    page = await context(member);
    await page.goto(`${site}/dashboard/documents`);
    await page.getByRole('heading', { name: 'Document Exchange with CRO' }).waitFor();
    await page.getByText('0 new from CRO', { exact: true }).waitFor();
    await screenshot(page, 'home-desktop');
    await page.getByRole('button', { name: 'View Documents', exact: true }).click();
    await page.getByText('No documents yet.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Upload File', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Upload Documents' });
    let failUpload = true, failShare = true, uploads = 0;
    page.on('request', r => { if (r.url().endsWith('/files/upload')) uploads++; });
    await page.route('**/files/upload', route => failUpload ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Upload temporarily unavailable.', errors: [] }) }) : route.continue());
    await dialog.getByLabel('Documents', { exact: true }).setInputFiles({ name: 'Research protocol.txt', mimeType: 'text/plain', buffer: Buffer.from('Protocol <script>not executed</script> & research notes') });
    await dialog.getByText('Upload temporarily unavailable.', { exact: true }).waitFor();
    failUpload = false;
    await dialog.getByRole('button', { name: 'Retry Research protocol.txt', exact: true }).click();
    await dialog.getByText('Uploaded', { exact: true }).waitFor();
    await dialog.getByLabel('Note (optional)').fill('Protocol for CRO review');
    await page.route('**/document-exchange/items', route => route.request().method() === 'POST' && failShare ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Sharing temporarily unavailable.', errors: [] }) }) : route.continue());
    await dialog.getByRole('button', { name: 'Share', exact: true }).click();
    await dialog.getByText('Sharing temporarily unavailable.', { exact: true }).waitFor();
    assert.equal(await dialog.getByLabel('Note (optional)').inputValue(), 'Protocol for CRO review');
    await screenshot(page, 'upload-retry-desktop');
    failShare = false;
    await dialog.getByRole('button', { name: 'Share', exact: true }).click();
    await page.getByText('Sent to CRO.', { exact: true }).waitFor();
    assert.equal(uploads, 2, 'Sharing retry must reuse the uploaded file');
    await page.reload(); await page.getByRole('button', { name: 'View Documents', exact: true }).click();
    await page.getByText('Research protocol.txt', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Preview Research protocol.txt', exact: true }).click();
    await page.getByRole('dialog').getByText('Protocol <script>not executed</script> & research notes', { exact: true }).waitFor();
    await screenshot(page, 'text-preview-desktop');
    await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click();
    const summary = await api(member, '/members/me/document-exchange');
    const threadId = summary.conversationId;
    const adminPage = await context(admin);
    await adminPage.goto(`${site}/admin/messages/${threadId}`);
    await adminPage.getByRole('button', { name: /Research protocol.txt/ }).click();
    const deadline = Date.now() + 5000;
    while (Date.now() < deadline && !await prisma.attachmentOpen.count({ where: { userId: admin.id } })) await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await prisma.attachmentOpen.count({ where: { userId: admin.id } }), 1);
    await adminPage.getByPlaceholder('Write your reply', { exact: false }).fill('CRO reviewed the protocol. Please see the attached image.');
    const inputs = adminPage.locator('input[type="file"]');
    assert.equal(await inputs.count(), 1);
    await inputs.setInputFiles({ name: 'CRO-image.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ1kAAAAASUVORK5CYII=', 'base64') });
    await adminPage.getByRole('button', { name: 'Send Reply', exact: true }).click();
    await adminPage.getByText('CRO reviewed the protocol. Please see the attached image.', { exact: true }).waitFor();
    await screenshot(adminPage, 'cro-reply-desktop');
    await page.getByText('1 new from CRO', { exact: true }).waitFor({ timeout: 40000 });
    await page.locator('span').filter({ hasText: /^Opened$/ }).waitFor();
    await page.getByRole('button', { name: 'Preview CRO-image.png', exact: true }).click();
    const image = page.getByRole('dialog').getByRole('img', { name: 'CRO-image.png', exact: true });
    await image.waitFor(); assert.ok(await image.evaluate(img => img.complete && img.naturalWidth > 0));
    await screenshot(page, 'image-preview-desktop');
    await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByText('0 new from CRO', { exact: true }).waitFor();
    const downloaded = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download CRO-image.png', exact: true }).click();
    assert.equal((await downloaded).suggestedFilename(), 'CRO-image.png');
    await page.getByLabel('Search documents').fill('research');
    await page.getByText('1 documents', { exact: true }).waitFor();
    await page.getByLabel('Direction', { exact: true }).selectOption('outgoing');
    await page.getByLabel('Opening status').selectOption('opened');
    await page.getByLabel('File type').selectOption('FILE');
    await page.getByText('Research protocol.txt', { exact: true }).waitFor();
    await screenshot(page, 'documents-desktop');
    await page.setViewportSize({ width: 390, height: 844 }); await screenshot(page, 'documents-mobile');
    await page.getByLabel('Search documents').fill('missing document');
    await page.getByText('No documents match these filters.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'View Messages', exact: true }).click();
    await page.getByRole('button', { name: /^Document Exchange/ }).click();
    await page.getByText('CRO reviewed the protocol. Please see the attached image.', { exact: true }).waitFor();
    await page.getByLabel('Reply', { exact: true }).fill('Thank you. This reply is from the exchange page.');
    await page.getByRole('button', { name: 'Send Reply', exact: true }).click();
    await page.getByText('Reply sent.', { exact: true }).waitFor();
    await screenshot(page, 'thread-mobile');
    await page.getByRole('button', { name: 'Send Message', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Send', exact: true }).click();
    await page.getByText('Write a message.', { exact: true }).waitFor();
    await page.getByLabel('Message', { exact: true }).fill('New exchange message');
    await page.getByRole('dialog').getByRole('button', { name: 'Send', exact: true }).click();
    await page.getByText('Sent to CRO.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Share Video', exact: true }).click();
    await page.getByLabel('Video URL').fill('javascript:alert(1)');
    await page.getByRole('dialog').getByRole('button', { name: 'Share', exact: true }).click();
    await page.getByText('Use an HTTP or HTTPS link without embedded credentials.', { exact: true }).waitFor();
    await page.getByLabel('Video URL').fill('https://vimeo.com/123');
    await page.getByRole('dialog').getByRole('button', { name: 'Share', exact: true }).click();
    await page.getByRole('link', { name: 'https://vimeo.com/123', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Request Meeting', exact: true }).click();
    await page.getByLabel('Meeting subject').fill('Protocol discussion');
    await page.getByLabel('Proposed date and time').fill('2035-06-10T09:00');
    await page.getByLabel('Timezone', { exact: true }).fill('Asia/Kolkata');
    await screenshot(page, 'meeting-mobile');
    await page.getByRole('dialog').getByRole('button', { name: 'Request', exact: true }).click();
    await page.getByText('Meeting request sent to CRO.', { exact: true }).waitFor();
    await page.getByRole('button', { name: /^Document Exchange/ }).click();
    await page.getByText('Proposed meeting:', { exact: false }).waitFor();
    await prisma.announcement.create({ data: { authorId: admin.id, subject: `${prefix} CRO Update`, body: 'Research update for active members.', audience: 'All Members', channel: 'Email', status: 'SENT', sentAt: new Date() } });
    await page.getByRole('button', { name: 'View Announcements', exact: true }).click();
    await page.getByRole('heading', { name: `${prefix} CRO Update`, exact: true }).waitFor();
    await screenshot(page, 'announcements-mobile');
    const file = await prisma.fileObject.findFirstOrThrow({ where: { uploaderId: member.id } });
    await prisma.message.create({ data: { conversationId: threadId, senderId: member.id, senderName: member.fullName, senderRole: 'MEMBER', body: 'Pagination browser fixture', attachments: { create: Array.from({ length: 12 }, () => ({ fileId: file.id })) } } });
    await page.getByRole('button', { name: 'View Documents', exact: true }).click();
    await page.getByLabel('Search documents').fill('Pagination browser fixture');
    await page.getByText('12 documents', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Next page', exact: true }).click();
    await page.getByText('2 / 2', { exact: true }).waitFor();
    await page.getByLabel('Rows per page').selectOption('25');
    await page.getByText('1 / 1', { exact: true }).waitFor();
    await page.route('**/members/me/documents?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Documents unavailable. Please retry.', errors: [] }) }));
    await page.getByLabel('Search documents').fill('retry');
    await page.getByText('Documents unavailable. Please retry.', { exact: false }).waitFor();
    await page.unroute('**/members/me/documents?**');
    await page.getByRole('button', { name: 'Retry', exact: true }).click();
    await page.getByText('No documents match these filters.', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ success: true, screenshots: output, flows: ['upload retry', 'share retry without duplicate upload', 'refresh persistence', 'text/image preview', 'download', 'CRO receipt and reply', 'polling', 'member reply', 'message validation', 'video validation', 'meeting timezone', 'announcements', 'search', 'filters', 'pagination', 'empty/error recovery', 'desktop/mobile'] }));
  } catch (error) {
    if (page) { await screenshot(page, 'failure').catch(() => {}); console.error((await page.locator('body').innerText()).slice(-5000)); }
    throw error;
  } finally {
    if (browser) await browser.close();
    const threads = await prisma.conversation.findMany({ where: { participants: { some: { userId: { in: users } } } }, select: { id: true } });
    await prisma.notification.deleteMany({ where: { OR: [{ userId: { in: users } }, ...threads.map(t => ({ link: { endsWith: `/${t.id}` } }))] } });
    await prisma.conversation.deleteMany({ where: { id: { in: threads.map(t => t.id) } } });
    await prisma.announcement.deleteMany({ where: { authorId: { in: users } } });
    const files = await prisma.fileObject.findMany({ where: { uploaderId: { in: users } } });
    for (const file of files) await fs.unlink(assertSafePath(file.storageKey)).catch(() => {});
    await prisma.fileObject.deleteMany({ where: { id: { in: files.map(f => f.id) } } });
    await prisma.auditLog.deleteMany({ where: { actorId: { in: users } } });
    await prisma.user.deleteMany({ where: { id: { in: users } } });
    await prisma.$disconnect();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
