// Run with the API and Vite servers active. Only this script's fixtures are removed.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
const { prisma } = require('../dist/config/database');
const { sha256, signAccessToken } = require('../dist/utils/security');
const base = process.env.EVENTS_API_URL || 'http://127.0.0.1:5002/api/v1';
const site = process.env.EVENTS_WEB_URL || 'http://127.0.0.1:5174';
const output = process.env.EVENTS_SCREENSHOT_DIR || '/private/tmp/events-browser';
const prefix = `events-browser-${crypto.randomUUID().slice(0, 8)}`;
let browser, admin;
const errors = [];
async function screenshot(page, name) {
  await page.screenshot({ path: path.join(output, `${name}.png`), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `${name}: page overflow`);
}
(async () => {
  try {
    await fs.mkdir(output, { recursive: true });
    admin = await prisma.user.create({ data: { fullName: 'Event Review Administrator', email: `${prefix}@example.test`, role: 'ADMIN', status: 'ACTIVE' } });
    const session = await prisma.session.create({ data: { userId: admin.id, tokenHash: sha256(crypto.randomUUID()), expiresAt: new Date(Date.now() + 3600000) } });
    const token = signAccessToken({ sub: admin.id, sessionId: session.id, role: 'ADMIN' });
    const api = async (url, method = 'GET', body) => {
      const response = await fetch(`${base}${url}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
      const result = await response.json(); assert.ok(response.ok, JSON.stringify(result)); return result.data;
    };
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await context.addInitScript(token => localStorage.setItem('ifsmhp.accessToken', token), token);
    const page = await context.newPage(); page.setDefaultTimeout(15000);
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(`${site}/admin/events/new`);
    await page.getByRole('heading', { name: 'Create New Event' }).waitFor();
    await screenshot(page, 'create-desktop');
    await page.getByLabel('Title', { exact: false }).fill(`${prefix} unfinished draft`);
    await page.getByRole('button', { name: 'Save Draft', exact: true }).click();
    await page.waitForURL(/\/admin\/events\/[^/]+\/edit$/);
    await page.getByRole('heading', { name: 'Edit Event', exact: true }).waitFor();
    const draftId = page.url().split('/').at(-2);
    await page.reload(); await page.getByRole('heading', { name: 'Edit Event', exact: true }).waitFor();
    assert.equal(await page.getByLabel('Title', { exact: false }).inputValue(), `${prefix} unfinished draft`);
    assert.equal((await api(`/admin/events/${draftId}`)).status, 'DRAFT');

    await page.goto(`${site}/admin/events/new`);
    await page.locator('#event-form button[type="submit"]').click();
    await page.getByText('Title must be at least 6 characters.', { exact: false }).first().waitFor();
    await page.getByLabel('Title', { exact: false }).fill(`${prefix} Research Workshop`);
    await page.getByLabel('Short Description', { exact: false }).fill('A practical workshop on research methods for our member community.');
    await page.getByLabel('Date', { exact: false }).first().fill('2030-06-12');
    await page.getByLabel('Start', { exact: false }).fill('14:00');
    await page.getByLabel(/^End/).fill('16:00');
    await page.getByLabel('Timezone', { exact: true }).selectOption('Asia/Kolkata');
    await page.getByLabel('Location / Virtual Room', { exact: false }).fill('Research Conference Room');
    await page.getByLabel('Organizing Team', { exact: false }).fill('Research Committee');
    await page.getByLabel('Contact Email', { exact: false }).fill('events@example.test');
    await page.getByLabel('Long Description / Agenda', { exact: false }).fill('An extended workshop covering research methods, data collection and practical exercises led by our invited speakers.');
    await page.getByPlaceholder('Speaker 1 name & affiliation').fill('Dr. Research Lead');
    await page.getByRole('button', { name: 'Workshop', exact: true }).click();
    await page.getByLabel('Audience', { exact: true }).selectOption('Public');
    await page.getByLabel('Capacity', { exact: true }).fill('25');
    await page.getByLabel('Event Cover Image', { exact: false }).setInputFiles({ name: 'event-cover.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ1kAAAAASUVORK5CYII=', 'base64') });
    await page.getByLabel('Send automated reminder email(s)', { exact: true }).uncheck();
    let fail = true, uploads = 0;
    page.on('request', r => { if (r.url().endsWith('/files/upload')) uploads++; });
    await page.route('**/api/v1/admin/events', route => route.request().method() === 'POST' && fail ? route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Event save temporarily unavailable.', errors: [] }) }) : route.continue());
    await page.getByRole('button', { name: 'Publish now', exact: true }).click();
    await page.getByText('Event save temporarily unavailable.', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Title', { exact: false }).inputValue(), `${prefix} Research Workshop`);
    fail = false;
    await page.getByRole('button', { name: 'Publish now', exact: true }).click();
    await page.waitForURL(/\/admin\/events\?tab=upcoming$/);
    await page.getByPlaceholder('Search events…').fill(`${prefix} Research Workshop`);
    await page.getByText('1 events · Page 1 of 1', { exact: true }).waitFor();
    await page.getByRole('link', { name: 'Edit', exact: true }).waitFor();
    assert.equal(uploads, 1, 'Retries should reuse the uploaded cover');
    await screenshot(page, 'list-desktop');
    await page.getByRole('link', { name: 'View', exact: true }).click();
    await page.getByRole('heading', { name: 'View Event' }).waitFor();
    assert.equal(await page.getByLabel('Title', { exact: false }).isDisabled(), true);
    assert.equal(await page.getByRole('img', { name: 'Event cover', exact: true }).evaluate(img => img.complete && img.naturalWidth > 0), true);
    await page.getByRole('link', { name: 'Edit Event', exact: true }).click();
    await page.getByRole('heading', { name: 'Edit Event' }).waitFor();
    const id = page.url().split('/').at(-2);
    await page.getByLabel('Title', { exact: false }).fill(`${prefix} Updated Workshop`);
    await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
    await page.getByText('Event saved.', { exact: true }).waitFor();
    await page.reload(); await page.getByRole('heading', { name: 'Edit Event' }).waitFor();
    assert.equal(await page.getByLabel('Title', { exact: false }).inputValue(), `${prefix} Updated Workshop`);
    await screenshot(page, 'edit-desktop');
    await page.setViewportSize({ width: 390, height: 844 });
    await screenshot(page, 'edit-mobile');
    await page.getByRole('button', { name: 'Cancel Event', exact: true }).click();
    await page.getByLabel('Reason for cancellation', { exact: false }).fill('The speaker is unavailable.');
    await page.getByLabel('Email cancellation notice', { exact: false }).uncheck();
    await page.getByRole('button', { name: 'Confirm Cancel Event', exact: true }).click();
    await page.getByText('Event cancelled.', { exact: true }).waitFor();
    assert.equal((await api(`/admin/events/${id}`)).status, 'CANCELLED');
    await page.goto(`${site}/admin/events?tab=past`);
    await page.getByPlaceholder('Search events…').fill(`${prefix} Updated Workshop`);
    await page.getByText('1 events · Page 1 of 1', { exact: true }).waitFor();
    await page.getByLabel('Delete event', { exact: true }).waitFor();
    await screenshot(page, 'list-mobile');
    await page.getByLabel('Delete event', { exact: true }).click();
    await page.getByRole('button', { name: 'Delete', exact: true }).click();
    await page.getByText('Event deleted.', { exact: true }).waitFor();
    await page.getByText('No events in this view.', { exact: true }).waitFor();
    for (let i = 0; i < 12; i++) await api('/admin/events', 'POST', { title: `${prefix} Paging ${i}` });
    await page.goto(`${site}/admin/events?tab=drafts`);
    await page.getByPlaceholder('Search events…').fill(`${prefix} Paging`);
    await page.getByText('12 events · Page 1 of 2', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Next', exact: true }).click();
    await page.getByText('12 events · Page 2 of 2', { exact: true }).waitFor();
    await page.getByLabel('Events per page').selectOption('25');
    await page.getByText('12 events · Page 1 of 1', { exact: true }).waitFor();
    await page.route('**/api/v1/admin/events?**', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Events unavailable. Retry.', errors: [] }) }));
    await page.reload(); await page.getByText('Events unavailable. Retry.', { exact: true }).waitFor();
    await page.unroute('**/api/v1/admin/events?**');
    await page.getByRole('button', { name: 'Retry', exact: true }).click();
    await page.getByRole('link', { name: 'Edit', exact: true }).first().waitFor();
    await page.goto(`${site}/admin/events/new`);
    await page.getByRole('heading', { name: 'Create New Event' }).waitFor();
    await screenshot(page, 'create-mobile');
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ success: true, screenshots: output, flows: ['create', 'draft', 'refresh', 'cover upload retry', 'view', 'edit', 'cancel', 'delete', 'search', 'pagination', 'error retry', 'desktop/mobile'] }));
  } finally {
    if (browser) await browser.close();
    if (admin) {
      await prisma.event.deleteMany({ where: { creatorId: admin.id } });
      const files = await prisma.fileObject.findMany({ where: { uploaderId: admin.id } });
      for (const file of files) await fs.unlink(path.join('uploads', file.storageKey)).catch(() => {});
      await prisma.fileObject.deleteMany({ where: { uploaderId: admin.id } });
      await prisma.auditLog.deleteMany({ where: { actorId: admin.id } });
      await prisma.user.delete({ where: { id: admin.id } });
    }
    await prisma.$disconnect();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
