// Run against a local API with automatic workers disabled. Only this script's fixtures are dispatched.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
process.env.SMTP_HOST = '';
const { prisma } = require('../dist/config/database');
const { sha256, signAccessToken } = require('../dist/utils/security');
const service = require('../dist/services/announcements.service');
const mail = require('../dist/services/mail.service');
const originalRecipients = service.recipientWhere;
const users = [];
service.recipientWhere = audience => ({ AND: [originalRecipients(audience), { id: { in: users.map(u => u.id) } }] });
mail.sendAnnouncementEmail = async () => { throw new Error('Browser fixtures must use in-app delivery only'); };
const { processAnnouncementJobs } = require('../dist/services/announcement-jobs.service');
const site = process.env.ANNOUNCEMENTS_WEB_URL || 'http://127.0.0.1:5177';
const base = process.env.ANNOUNCEMENTS_API_URL || 'http://127.0.0.1:5005/api/v1';
const output = '/private/tmp/member-announcements-browser';
const prefix = `member-ann-${crypto.randomUUID().slice(0, 8)}`;
let browser, memberPage, editor;
const errors = [];
async function actor(role) {
  const user = await prisma.user.create({ data: { role, status: 'ACTIVE', fullName: `Announcement Test ${role}`, email: `${prefix}-${role}@example.test`, ...(role === 'MEMBER' ? { memberProfile: { create: { professionalType: 'Academic Researcher', institution: 'Test Institute', country: 'India' } } } : {}) } });
  users.push(user);
  const session = await prisma.session.create({ data: { userId: user.id, tokenHash: sha256(crypto.randomUUID()), expiresAt: new Date(Date.now() + 3600000) } });
  return { ...user, token: signAccessToken({ sub: user.id, role, sessionId: session.id }) };
}
async function screenshot(page, name) {
  await page.screenshot({ path: path.join(output, `${name}.png`), fullPage: !(await page.getByRole('dialog').count()) });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}: page overflow`);
  for (const dialog of await page.getByRole('dialog').all()) assert.ok(await dialog.evaluate(n => n.scrollWidth <= n.clientWidth), `${name}: dialog overflow`);
}
(async () => {
  try {
    await fs.mkdir(output, { recursive: true });
    const admin = await actor('ADMIN'), member = await actor('MEMBER');
    const api = async (suffix, method = 'GET', data) => {
      const response = await fetch(`${base}${suffix}`, { method, headers: { Authorization: `Bearer ${admin.token}`, 'Content-Type': 'application/json' }, ...(data ? { body: JSON.stringify(data) } : {}) });
      const json = await response.json(); assert.ok(response.ok, JSON.stringify(json)); return json.data;
    };
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const context = async who => {
      const c = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
      await c.addInitScript(token => localStorage.setItem('ifsmhp.accessToken', token), who.token);
      const p = await c.newPage(); p.setDefaultTimeout(15000); p.on('pageerror', e => errors.push(e.message)); return p;
    };
    editor = await context(admin); memberPage = await context(member);
    await memberPage.goto(`${site}/dashboard/notifications`);
    await memberPage.getByText('No notifications to display.', { exact: true }).waitFor();
    await screenshot(memberPage, 'empty-desktop');
    await editor.goto(`${site}/admin/announcements`);
    await editor.getByRole('button', { name: 'New Announcement', exact: true }).click();
    const subject = `${prefix} Research update`;
    await editor.getByLabel('Subject', { exact: false }).fill(subject);
    await editor.getByLabel('Message Body', { exact: false }).fill('**Research update**\n\nImportant information for members. <script>never execute</script>');
    await editor.getByLabel('Delivery Channel', { exact: true }).selectOption('In-App Only');
    await editor.getByLabel('Expiration (optional)', { exact: true }).fill('2035-06-10T10:00');
    await editor.getByLabel('Timezone (IANA)', { exact: true }).fill('Asia/Kolkata');
    await editor.getByRole('button', { name: 'Save Draft', exact: true }).click();
    await editor.getByText('Draft saved.', { exact: true }).waitFor();
    const draft = await prisma.announcement.findFirstOrThrow({ where: { authorId: admin.id, subject } });
    assert.equal(draft.expiresAt.toISOString(), '2035-06-10T04:30:00.000Z');
    await editor.getByRole('radio', { name: /Send Immediately/ }).check();
    await screenshot(editor, 'admin-composer-desktop');
    await editor.getByRole('button', { name: 'Broadcast Now', exact: true }).click();
    await editor.getByText('Broadcast queued. Delivery outcomes will appear as processing completes.', { exact: true }).waitFor();
    await processAnnouncementJobs(new Date(), draft.id);
    await memberPage.getByRole('button', { name: new RegExp(subject) }).waitFor({ timeout: 40000 });
    await screenshot(memberPage, 'notification-desktop');
    await memberPage.getByRole('button', { name: new RegExp(subject) }).click();
    const dialog = memberPage.getByRole('dialog');
    await dialog.getByRole('button', { name: 'Mark unread', exact: true }).waitFor();
    assert.ok((await dialog.innerText()).includes('<script>never execute</script>'));
    const receipt = await prisma.announcementDelivery.findFirstOrThrow({ where: { announcementId: draft.id, recipientUserId: member.id } });
    assert.ok(receipt.openedAt);
    await screenshot(memberPage, 'detail-desktop');
    await memberPage.setViewportSize({ width: 390, height: 844 }); await screenshot(memberPage, 'detail-mobile');
    await dialog.getByRole('button', { name: 'Mark unread', exact: true }).click();
    await dialog.getByRole('button', { name: 'Mark read', exact: true }).waitFor();
    await memberPage.keyboard.press('Escape');
    await dialog.waitFor({ state: 'detached' });
    assert.ok(await memberPage.getByRole('button', { name: new RegExp(subject) }).evaluate(n => n === document.activeElement), 'Closing detail restores focus');
    await screenshot(memberPage, 'notification-mobile');
    await memberPage.goto(`${site}/dashboard/documents`);
    await memberPage.getByRole('button', { name: 'View Announcements', exact: true }).click();
    await memberPage.getByLabel('Search announcements').fill(prefix);
    await memberPage.getByRole('button', { name: new RegExp(subject) }).waitFor();
    await screenshot(memberPage, 'exchange-mobile');
    await memberPage.getByRole('button', { name: new RegExp(subject) }).click();
    await dialog.getByRole('button', { name: 'Mark unread', exact: true }).waitFor();
    assert.equal((await prisma.announcementDelivery.findUniqueOrThrow({ where: { id: receipt.id } })).openedAt.toISOString(), receipt.openedAt.toISOString());
    await memberPage.keyboard.press('Escape');
    await memberPage.getByLabel('Announcement status').selectOption('READ');
    await memberPage.getByRole('button', { name: new RegExp(subject) }).waitFor();
    await memberPage.getByLabel('Search announcements').fill(`${prefix} missing`);
    await memberPage.getByText('No announcements to display.', { exact: true }).waitFor();
    await screenshot(memberPage, 'filtered-empty-mobile');
    await memberPage.getByLabel('Search announcements').fill(prefix);
    await memberPage.getByRole('button', { name: new RegExp(subject) }).waitFor();
    let fail = true;
    await memberPage.route(`**/members/me/announcements/${draft.id}`, route => fail ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Temporary fixture error' }) }) : route.continue());
    await memberPage.getByRole('button', { name: new RegExp(subject) }).click();
    await dialog.getByRole('button', { name: 'Retry', exact: true }).waitFor();
    await screenshot(memberPage, 'retry-mobile');
    fail = false; await dialog.getByRole('button', { name: 'Retry', exact: true }).click();
    await dialog.getByRole('button', { name: 'Mark unread', exact: true }).waitFor();
    await memberPage.keyboard.press('Escape');
    await memberPage.setViewportSize({ width: 1440, height: 1000 });
    for (let i = 0; i < 11; i++) await prisma.announcement.create({ data: { authorId: admin.id, subject: `${prefix} Legacy ${i}`, body: 'Historical member announcement', audience: 'Members Only', channel: 'In-App Only', status: 'SENT', sentAt: new Date() } });
    await memberPage.getByLabel('Announcement status').selectOption('All');
    await memberPage.getByRole('button', { name: 'Next page', exact: true }).click();
    await memberPage.getByText('2 / 2', { exact: true }).waitFor();
    await screenshot(memberPage, 'exchange-page-two');
    await memberPage.getByRole('button', { name: 'Previous page', exact: true }).click();
    await memberPage.getByText('1 / 2', { exact: true }).waitFor();
    await screenshot(memberPage, 'exchange-desktop');
    await memberPage.getByRole('button', { name: new RegExp(subject) }).click();
    await dialog.getByRole('button', { name: 'Mark unread', exact: true }).waitFor();
    await editor.reload();
    await editor.getByPlaceholder('Search announcements', { exact: false }).fill(subject);
    const card = editor.locator('div.rounded-xl').filter({ has: editor.getByText(subject, { exact: true }) });
    await card.getByRole('button', { name: 'Delete', exact: true }).click();
    await editor.getByRole('dialog').getByRole('button', { name: 'Confirm Delete', exact: true }).click();
    await editor.getByText('Announcement deleted.', { exact: true }).waitFor();
    await dialog.getByText('Announcement not found', { exact: false }).waitFor({ timeout: 40000 });
    assert.equal(await dialog.getByText('Research update', { exact: true }).count(), 0);
    await screenshot(memberPage, 'deleted-detail');
    assert.equal(await prisma.announcement.count({ where: { id: draft.id, deletedAt: { not: null } } }), 1);
    assert.deepEqual(errors, []);
    console.log(`Browser verification passed. Screenshots: ${output}`);
  } catch (error) {
    if (memberPage) await screenshot(memberPage, 'failure-member').catch(() => {});
    if (editor) await screenshot(editor, 'failure-admin').catch(() => {});
    console.error(error); process.exitCode = 1;
  } finally {
    if (browser) await browser.close();
    const ids = users.map(u => u.id);
    const rows = await prisma.announcement.findMany({ where: { authorId: { in: ids } }, select: { id: true } });
    await prisma.notification.deleteMany({ where: { userId: { in: ids } } });
    await prisma.auditLog.deleteMany({ where: { OR: [{ actorId: { in: ids } }, { entity: { in: rows.map(r => `Announcement ${r.id}`) } }] } });
    await prisma.announcement.deleteMany({ where: { id: { in: rows.map(r => r.id) } } });
    await prisma.user.deleteMany({ where: { id: { in: ids } } });
    await prisma.$disconnect();
  }
})();
