// Only run against an isolated database/API, with SMTP disabled.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
const { prisma } = require('../dist/config/database');
const { hashPassword } = require('../dist/utils/security');
const site = process.env.SETTINGS_WEB_URL || 'http://127.0.0.1:5179', base = process.env.SETTINGS_API_URL || 'http://127.0.0.1:5007/api/v1';
const out = process.env.SETTINGS_SCREENSHOT_DIR || '/private/tmp/ifsmhp-settings-browser';
const checks = [], errors = [];
let user, browser, context, page, token, original, revisions;
async function api(url, method = 'GET', body) { const r = await context.request.fetch(base + url, { method, headers: { Authorization: `Bearer ${token}` }, ...(body ? { data: body } : {}) }); const j = await r.json(); assert.ok(r.ok(), JSON.stringify(j)); return j.data; }
const ready = () => page.getByRole('heading', { name: 'Organization Identity', exact: true }).waitFor();
async function tab(name) { await page.getByRole('button', { name: new RegExp('^' + name) }).click(); }
async function save(name, expected = 200) { const wait = page.waitForResponse(r => r.url().includes('/admin/settings/') && r.request().method() === 'PATCH'); await page.getByRole('button', { name: 'Save ' + name, exact: true }).first().click(); const r = await wait; assert.equal(r.status(), expected); if (expected === 200) await page.getByRole('status').filter({ hasText: 'Settings saved.' }).waitFor(); return r; }
async function shot(name) { assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), name + ' horizontal overflow'); await page.screenshot({ path: path.join(out, name + '.png'), fullPage: false }); }
async function run() {
  await fs.mkdir(out, { recursive: true }); original = await prisma.platformSetting.findMany(); revisions = await prisma.settingRevision.findMany();
  user = await prisma.user.create({ data: { email: `settings-browser-${crypto.randomUUID()}@example.test`, fullName: 'Settings Browser Reviewer', role: 'ADMIN', status: 'ACTIVE', passwordHash: await hashPassword('Browser-settings-2026!') } });
  browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) }); context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const login = await context.request.post(base + '/auth/login', { data: { email: user.email, password: 'Browser-settings-2026!' } }); assert.equal(login.status(), 200); token = (await login.json()).data.accessToken;
  await context.addInitScript(t => localStorage.setItem('ifsmhp.accessToken', t), token); page = await context.newPage(); page.setDefaultTimeout(15000); page.on('pageerror', e => errors.push(e.message));
  await page.goto(site + '/admin/settings'); await ready();
  await page.getByLabel('Short name / acronym', { exact: true }).fill('Research Forum');
  await page.getByLabel('Contact email', { exact: true }).fill('office@example.test'); await page.getByLabel('Contact phone', { exact: true }).fill('+44 1234 567890'); await page.getByLabel('Office address', { exact: true }).fill('Research Office\nLondon');
  await page.getByLabel('Default timezone', { exact: true }).fill('Asia/Kolkata'); await page.getByLabel('Formatting locale').selectOption('en-GB'); await page.getByLabel('Date format', { exact: true }).selectOption('YYYY-MM-DD');
  await page.getByLabel('Display a maintenance notice on public pages').check(); await page.getByLabel('Notice message', { exact: true }).fill('Scheduled maintenance notice — all services remain available.');
  await tab('Review & SLA'); await page.getByLabel('Publications: review threshold (days)', { exact: true }).fill('15'); await tab('General'); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'Research Forum'); await save('General');
  await tab('Review & SLA'); assert.equal(await page.getByLabel('Publications: review threshold (days)').inputValue(), '15'); await save('Review & SLA');
  await page.reload(); await ready(); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'Research Forum'); checks.push('Section saves persist, survive reload and preserve drafts in other tabs');
  await shot('settings-desktop');
  await page.getByRole('button', { name: 'Reset to defaults', exact: true }).first().click(); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'IFSMHP'); assert.equal((await api('/admin/settings')).values.general.shortName, 'Research Forum'); await page.reload(); await ready(); checks.push('Reset only changes the draft until saved');
  await page.route('**/admin/settings/general', async route => { if (route.request().method() === 'PATCH') { await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, message: 'Test service unavailable' }) }); } else await route.continue(); });
  await page.getByLabel('Short name / acronym').fill('Preserved after failure'); await save('General', 503); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'Preserved after failure'); await page.unroute('**/admin/settings/general'); await save('General'); checks.push('Recoverable failures preserve inputs and retry succeeds');
  await page.getByLabel('Default timezone').fill('Invalid/Zone'); await save('General', 422); await page.getByText('Choose a valid IANA timezone.', { exact: true }).waitFor(); assert.equal(await page.getByLabel('Default timezone').inputValue(), 'Invalid/Zone'); await page.getByLabel('Default timezone').fill('Asia/Kolkata');
  await page.getByLabel('Short name / acronym').fill('Concurrent draft'); const current = await api('/admin/settings'); await api('/admin/settings/general', 'PATCH', { expectedRevision: current.sections.general.revision, values: { shortName: 'Other reviewer' } }); await save('General', 409); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'Concurrent draft'); await page.getByRole('button', { name: 'Load latest values', exact: true }).click(); await page.getByRole('button', { name: 'I have reviewed the latest values', exact: true }).click(); await save('General'); assert.equal((await api('/admin/settings')).values.general.shortName, 'Concurrent draft'); checks.push('Validation and concurrent-tab conflicts preserve drafts and require explicit review');
  // A read begun before a successful mutation must not overwrite it.
  let release, started; const held = new Promise(r => { release = r; }), pending = new Promise(r => { started = r; }); const old = await api('/admin/settings');
  await page.route('**/admin/settings', async route => { if (route.request().method() === 'GET') { started(); await held; await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, data: old }) }).catch(() => {}); } else await route.continue(); });
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await pending; await page.getByLabel('Short name / acronym').fill('Current saved value'); await save('General'); release(); await page.unroute('**/admin/settings'); assert.equal(await page.getByLabel('Short name / acronym').inputValue(), 'Current saved value'); checks.push('Stale reads cannot restore pre-mutation values');
  await tab('Events & Calendar'); await page.getByLabel('Default capacity (0 = unlimited)', { exact: true }).fill('42'); await page.getByLabel('Default reminder (days before event)', { exact: true }).selectOption('7'); await page.getByLabel('Enable registration by default on new events').uncheck(); await save('Events & Calendar');
  await tab('Communications'); await page.getByLabel('Enable SAB preview and sign-off by default for new drafts').check(); await save('Communications');
  await tab('Security & Privacy'); await page.getByLabel('DPO / privacy contact email').fill('privacy@example.test'); await save('Security & Privacy');
  await page.goto(site + '/admin/events/new'); await page.getByLabel('Timezone', { exact: true }).waitFor(); assert.equal(await page.getByLabel('Timezone', { exact: true }).inputValue(), 'Asia/Kolkata'); assert.equal(await page.getByLabel(/Capacity/).inputValue(), '42'); checks.push('New event editor inherits persisted defaults');
  await page.goto(site + '/admin/announcements'); await page.getByRole('button', { name: 'New Announcement', exact: true }).click(); const sab = page.getByLabel('Send SAB preview first — wait for sign-off before scheduling full broadcast.', { exact: true }); await sab.waitFor(); await page.waitForFunction(() => document.querySelector('#sab-approval')?.checked === true); checks.push('New announcement inherits the sign-off default');
  const publicPage = await context.newPage(); await publicPage.goto(site + '/contact'); await publicPage.getByText('Scheduled maintenance notice — all services remain available.', { exact: true }).waitFor(); await publicPage.getByRole('link', { name: 'privacy@example.test', exact: true }).waitFor(); await publicPage.close(); checks.push('Public branding, contact and banner use saved values');
  await page.goto(site + '/admin/settings'); await ready(); await tab('Billing & Finance'); assert.equal(await page.getByRole('button', { name: 'Save Billing & Finance', exact: true }).first().isDisabled(), true); await tab('Backup & Audit'); const downloadWait = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export audit (all time, CSV)', exact: true }).click(); const download = await downloadWait; const file = await download.path(); assert.ok((await fs.readFile(file, 'utf8')).includes('PlatformSettingsUpdated')); checks.push('Unavailable sections cannot save; real all-time CSV download works');
  await page.getByRole('link', { name: 'View configuration audit trail', exact: true }).click(); await page.waitForFunction(() => document.querySelector('select[aria-label="Module"]')?.value === 'SETTINGS'); assert.equal(await page.getByRole('combobox', { name: 'Module', exact: true }).inputValue(), 'SETTINGS'); checks.push('Configuration audit link initializes module filter');
  await page.goto(site + '/admin/settings'); await ready(); await page.setViewportSize({ width: 390, height: 844 }); await page.waitForFunction(() => document.querySelector('aside')?.getBoundingClientRect().right <= 1); await shot('settings-mobile'); await tab('Events & Calendar'); await page.getByRole('heading', { name: 'Event Defaults & RSVP', exact: true }).scrollIntoViewIfNeeded(); await shot('settings-mobile-events'); checks.push('Desktop and mobile layouts have no horizontal overflow');
  await prisma.session.updateMany({ where: { userId: user.id }, data: { revokedAt: new Date() } }); await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await page.getByRole('alert').filter({ hasText: 'Invalid or expired credentials' }).waitFor(); assert.equal(await page.getByLabel('Default capacity (0 = unlimited)', { exact: true }).count(), 0); await shot('settings-access-revoked'); checks.push('Session revocation clears protected settings and displays an access error');
  assert.deepEqual(errors, []); await fs.writeFile(path.join(out, 'results.json'), JSON.stringify({ checks, errors }, null, 2)); console.log(JSON.stringify({ checks, errors }, null, 2));
}
run().catch(async error => { console.error(error); if (page) { await page.screenshot({ path: path.join(out, 'failure.png') }).catch(() => {}); await fs.writeFile(path.join(out, 'failure.html'), await page.content()).catch(() => {}); } process.exitCode = 1; }).finally(async () => {
  if (context) await context.close(); if (browser) await browser.close();
  if (original) { await prisma.platformSetting.deleteMany(); if (original.length) await prisma.platformSetting.createMany({ data: original }); await prisma.settingRevision.deleteMany(); if (revisions.length) await prisma.settingRevision.createMany({ data: revisions }); }
  if (user) { await prisma.auditLog.deleteMany({ where: { actorId: user.id } }); await prisma.user.delete({ where: { id: user.id } }); } await prisma.$disconnect();
});
