import { communityChanged, useCommunityFeed } from '../../../hooks/useCommunityResource';
import { useDebouncedValue } from '../../../hooks/useDebouncedValue';
import CommunityLoadMore from '../../../components/community/CommunityLoadMore';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { ArrowLeft, Lock, LockOpen, MessageSquare, RefreshCw, Search } from 'lucide-react';
import { normalizeError } from '../../../api/client';
import Button from '../../../components/common/Button';
import ChatComposer from '../../../components/community/ChatComposer';
import ChatMessageItem from '../../../components/community/ChatMessageItem';
import CommunityPageSkeleton from '../../../components/community/CommunityPageSkeleton';
import ConfirmationDialog from '../../../components/community/ConfirmationDialog';
import EmptyCommunityState from '../../../components/community/EmptyCommunityState';
import { CommunityToast, PageHeading, controlClass, formatDate, panelClass } from '../../../components/community/AdminCommunityUi';
import { communityAdminService } from '../../../services/communityAdminService';
import type { CommunityMessage } from '../../../types/community';

type MobilePanel = 'communities' | 'conversations' | 'messages';
export default function AdminCommunityChatsPage() {
  const [communityId, setCommunityId] = useState(''); const [conversationId, setConversationId] = useState('');
  const [communitySearch, setCommunitySearch] = useState(''); const [conversationSearch, setConversationSearch] = useState('');
  const searchCommunity = useDebouncedValue(communitySearch); const searchConversation = useDebouncedValue(conversationSearch);
  const [busy, setBusy] = useState(false); const [replyTo, setReplyTo] = useState<CommunityMessage | null>(null); const [deleting, setDeleting] = useState<CommunityMessage | null>(null);
  const [panel, setPanel] = useState<MobilePanel>('communities'); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null); const nearBottom = useRef(true); const olderHeight = useRef<number | null>(null);
  const communityList = useCommunityFeed(`chat-communities:${searchCommunity}`, page => communityAdminService.getCommunities({ page, limit: 50, search: searchCommunity }));
  const conversationList = useCommunityFeed(communityId ? `chat-conversations:${communityId}:${searchConversation}` : null, page => communityAdminService.getConversations({ page, limit: 50, communityId, search: searchConversation }), 8000);
  const communities = communityList.items.map(c => ({ id: c.id, name: c.name, unread: c.unreadCount ?? 0 }));
  const conversations = conversationList.items, visibleConversations = conversations;
  const selected = conversations.find(c => c.id === conversationId) ?? null;
  const messageList = useCommunityFeed(selected ? `admin-messages:${selected.id}` : null, page => communityAdminService.getConversationMessages(selected!.id, { page, limit: 100 }), 8000, true);
  const messages = messageList.items, loading = communityList.loading, messageLoading = messageList.loading;
  const error = communityList.error || conversationList.error || messageList.error;
  const loadConversations = async () => { await Promise.all([communityList.refresh(), conversationList.refresh()]); };
  const refresh = async () => { communityChanged(); await Promise.all([communityList.refresh(), conversationList.refresh(), messageList.refresh()]); };
  useEffect(() => { setReplyTo(null); setDeleting(null); nearBottom.current = true; }, [communityId, conversationId]);
  useEffect(() => { if (replyTo && !messageLoading && !messages.some(m => m.id === replyTo.id && !m.isDeleted && !m.isHidden)) setReplyTo(null); }, [messageLoading, messages, replyTo]);
  useLayoutEffect(() => {
    const el = scrollRef.current; if (!el) return;
    if (olderHeight.current !== null) { el.scrollTop += el.scrollHeight - olderHeight.current; olderHeight.current = null; }
    else if (nearBottom.current) el.scrollTop = el.scrollHeight;
  }, [messageList.data]);
  const notify = (message: string, isError = false) => { setToast({ message, error: isError }); window.setTimeout(() => setToast(null), 3500); };
  const patchMessage = async (message: CommunityMessage, patch: { isPinned?: boolean; isHidden?: boolean; isRead?: boolean }) => { if (busy) return; setBusy(true); try { await communityAdminService.updateMessage(message.id, patch); await refresh(); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const send = async (content: string, files: File[]) => { if (!selected || busy) return false; setBusy(true); try { await communityAdminService.sendAdminMessage(selected.id, { content, attachments: files, replyToId: replyTo?.id }); setReplyTo(null); await refresh(); return true; } catch (failure) { notify(normalizeError(failure).message, true); return false; } finally { setBusy(false); } };
  const toggleLock = async () => { if (!selected || busy) return; setBusy(true); try { await communityAdminService.updateConversation(selected.id, { isLocked: !selected.isLocked }); await refresh(); notify(selected.isLocked ? 'Conversation unlocked.' : 'Conversation locked.'); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const deleteMessage = async () => { if (!deleting || busy) return; setBusy(true); try { await communityAdminService.deleteMessage(deleting.id); setDeleting(null); await refresh(); notify('Message deleted.'); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  return <div className="space-y-6"><PageHeading title="Community Chats" description="Monitor conversations, respond as an administrator, and moderate messages." actions={<Button variant="outline" onClick={() => void loadConversations()}><RefreshCw className="h-4 w-4" />Refresh</Button>} />{error && !communities.length ? <EmptyCommunityState title="" error={error} retry={() => void loadConversations()} /> : <div className={`${panelClass} grid h-[650px] overflow-hidden lg:grid-cols-[240px_300px_minmax(0,1fr)]`}>
    <aside className={`${panel !== 'communities' ? 'hidden lg:block' : ''} overflow-y-auto border-r border-paper-border`}><PanelHeader title="Communities" query={communitySearch} setQuery={setCommunitySearch} />{loading ? <div className="p-3"><CommunityPageSkeleton rows={4} /></div> : !communities.length ? <Empty text="No communities" /> : <div className="p-2">{communities.map((community) => <button type="button" key={community.id} onClick={() => { setCommunityId(community.id); setConversationId(''); setPanel('conversations'); }} className={`mb-1 flex w-full items-center justify-between rounded-lg p-3 text-left text-sm ${communityId === community.id ? 'bg-forum-700 text-white' : 'text-forum-900 hover:bg-forum-50'}`}><span className="truncate">{community.name}</span>{community.unread > 0 && <span className="rounded-full bg-brass-500 px-2 py-0.5 text-xs text-white">{community.unread}</span>}</button>)}<CommunityLoadMore more={communityList.hasMore} load={communityList.loadMore} /></div>}</aside>
    <aside className={`${panel !== 'conversations' ? 'hidden lg:block' : ''} overflow-y-auto border-r border-paper-border`}><div className="lg:hidden"><Back onClick={() => setPanel('communities')} /></div><PanelHeader title="Conversations" query={conversationSearch} setQuery={setConversationSearch} />{conversationList.loading ? <div className="p-3"><CommunityPageSkeleton /></div> : conversationList.error ? <EmptyCommunityState title="" error={conversationList.error} retry={() => void conversationList.refresh()} /> : !communityId ? <Empty text="Select a community" /> : !visibleConversations.length ? <Empty text="No conversations" /> : <div className="p-2">{visibleConversations.map((conversation) => <button type="button" key={conversation.id} onClick={() => { setConversationId(conversation.id); setPanel('messages'); }} className={`mb-1 w-full rounded-lg p-3 text-left ${conversationId === conversation.id ? 'bg-forum-50 ring-1 ring-forum-200' : 'hover:bg-forum-50'}`}><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-sm font-medium text-forum-900">{conversation.title}</span>{conversation.isLocked && <Lock className="h-3.5 w-3.5 text-ink-subtle" />}{conversation.unreadCount > 0 && <span className="rounded-full bg-brass-500 px-1.5 text-xs text-white">{conversation.unreadCount}</span>}</div><p className="mt-1 truncate text-xs text-ink-muted">{conversation.lastMessage?.content ?? 'No messages yet'}</p><p className="mt-1 text-[11px] text-ink-subtle">{conversation.messageCount} messages · {formatDate(conversation.updatedAt)}</p></button>)}<CommunityLoadMore more={conversationList.hasMore} load={conversationList.loadMore} /></div>}</aside>
    <section className={`${panel !== 'messages' ? 'hidden lg:flex' : 'flex'} min-h-0 flex-col`}>{!selected ? <div className="flex flex-1 items-center justify-center text-center text-sm text-ink-muted"><div><MessageSquare className="mx-auto mb-2 h-8 w-8" />Select a conversation</div></div> : <><header className="flex items-center justify-between gap-3 border-b border-paper-border p-3"><div className="flex min-w-0 items-center gap-2"><div className="lg:hidden"><Back onClick={() => setPanel('conversations')} /></div><div className="min-w-0"><h2 className="truncate font-semibold text-forum-900">{selected.title}</h2><p className="truncate text-xs text-ink-muted">{selected.communityName}</p></div></div><Button size="sm" variant="outline" onClick={() => void toggleLock()} disabled={busy}>{selected.isLocked ? <LockOpen className="h-4 w-4" /> : <Lock className="h-4 w-4" />}{selected.isLocked ? 'Unlock' : 'Lock'}</Button></header><div ref={scrollRef} onScroll={(e) => { const el = e.currentTarget; nearBottom.current = el.scrollHeight - el.scrollTop - el.clientHeight < 120; if (el.scrollTop < 40 && !nearBottom.current && messageList.hasMore) { olderHeight.current = el.scrollHeight; void messageList.loadMore(); } }} className="flex-1 space-y-3 overflow-y-auto bg-forum-50/30 p-3 sm:p-4">{messageLoading ? <CommunityPageSkeleton /> : messageList.error && !messages.length ? <EmptyCommunityState title="" error={messageList.error} retry={() => void messageList.refresh()} /> : !messages.length ? <Empty text="No messages yet" /> : messages.map((message) => <ChatMessageItem key={message.id} message={message} disabled={busy} onReply={() => setReplyTo(message)} onPatch={(patch) => void patchMessage(message, patch)} onDelete={() => setDeleting(message)} />)}</div><ChatComposer key={selected.id} locked={selected.isLocked || !messageList.data} busy={busy} replyTo={replyTo} cancelReply={() => setReplyTo(null)} send={send} /></>}</section>
  </div>}{deleting && <ConfirmationDialog title="Delete message?" description="The message will be deleted from this conversation." confirmLabel="Delete" busy={busy} onClose={() => setDeleting(null)} onConfirm={() => void deleteMessage()} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}</div>;
}
function PanelHeader({ title, query, setQuery }: { title: string; query: string; setQuery: (value: string) => void }) { return <header className="border-b border-paper-border p-3"><h2 className="font-semibold text-forum-900">{title}</h2><label className="relative mt-2 block"><span className="sr-only">Search {title}</span><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-ink-subtle" /><input value={query} onChange={(e) => setQuery(e.target.value)} className={`${controlClass} w-full py-2 pl-8 text-xs`} placeholder={`Search ${title.toLowerCase()}`} /></label></header>; }
function Empty({ text }: { text: string }) { return <p className="p-8 text-center text-sm text-ink-muted">{text}</p>; }
function Back({ onClick }: { onClick: () => void }) { return <button type="button" title="Back" aria-label="Back" onClick={onClick} className="rounded-md p-2 text-forum-700 hover:bg-forum-50"><ArrowLeft className="h-4 w-4" /></button>; }
