import { useCallback, useEffect, useState } from 'react';
import { Eye, Gavel, RefreshCw, Search } from 'lucide-react';
import { normalizeError } from '../../../api/client';
import Button from '../../../components/common/Button';
import CommunityPageSkeleton from '../../../components/community/CommunityPageSkeleton';
import CommunityReportDetailsDrawer from '../../../components/community/CommunityReportDetailsDrawer';
import CommunityStatusBadge from '../../../components/community/CommunityStatusBadge';
import EmptyCommunityState from '../../../components/community/EmptyCommunityState';
import ModerationActionModal from '../../../components/community/ModerationActionModal';
import { CommunityPagination, CommunityToast, PageHeading, controlClass, formatDate, panelClass } from '../../../components/community/AdminCommunityUi';
import { useDebouncedValue } from '../../../hooks/useDebouncedValue';
import { communityAdminService } from '../../../services/communityAdminService';
import type { CommunityReport, PaginatedCommunityResult, ReportStatus } from '../../../types/community';

export default function AdminCommunityModerationPage() {
  const [result, setResult] = useState<PaginatedCommunityResult<CommunityReport> | null>(null); const [communities, setCommunities] = useState<{ id: string; name: string }[]>([]); const [query, setQuery] = useState(''); const search = useDebouncedValue(query); const [filters, setFilters] = useState({ status: '', communityId: '', dateFrom: '' }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [details, setDetails] = useState<CommunityReport | null>(null); const [action, setAction] = useState<{ report: CommunityReport; initial?: string } | null>(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  useEffect(() => { let active = true; communityAdminService.getCommunities({ limit: 100, sort: 'name:asc' }).then((response) => { if (active) setCommunities(response.items.map((community) => ({ id: community.id, name: community.name }))); }).catch(() => { /* filter stays empty; reports remain usable */ }); return () => { active = false; }; }, []);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setResult(await communityAdminService.getReports({ page, limit: 10, search, ...filters })); } catch (failure) { setError(normalizeError(failure).message); } finally { setLoading(false); } }, [filters, page, search]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { setPage(1); }, [search, filters]);
  const notify = (message: string, isError = false) => { setToast({ message, error: isError }); window.setTimeout(() => setToast(null), 3500); };
  const status = async (report: CommunityReport, next: ReportStatus, notes?: string) => { setBusy(true); try { await communityAdminService.updateReport(report.id, { status: next, resolutionNotes: notes }); notify(`Report marked ${next.toLowerCase().replace('_', ' ')}.`); setAction(null); await load(); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const moderate = async (kind: string, notes: string) => { if (!action) return; if (kind === 'RESOLVE_REPORT') { await status(action.report, 'RESOLVED', notes); return; } if (kind === 'DISMISS_REPORT') { await status(action.report, 'DISMISSED', notes); return; } setBusy(true); try { await communityAdminService.createModerationAction(action.report.id, { action: kind, notes }); notify('Moderation action applied.'); setAction(null); await load(); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  return <div className="space-y-6"><PageHeading title="Reports & Moderation" description="Review reports and take documented action on unsafe content or members." actions={<Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</Button>} /><div className={`${panelClass} grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4`}><label className="relative"><span className="sr-only">Search reports</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-ink-subtle" /><input className={`${controlClass} w-full pl-9`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search reports" /></label><select aria-label="Status" className={controlClass} value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))}><option value="">All statuses</option>{['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED'].map((v) => <option key={v}>{v}</option>)}</select><select aria-label="Community" className={controlClass} value={filters.communityId} onChange={(e) => setFilters((f) => ({ ...f, communityId: e.target.value }))}><option value="">All communities</option>{communities.map((community) => <option key={community.id} value={community.id}>{community.name}</option>)}</select><input aria-label="Reported since" title="Reported since" type="date" className={controlClass} value={filters.dateFrom} onChange={(e) => setFilters((f) => ({ ...f, dateFrom: e.target.value }))} /></div>
    <section className={panelClass}>{loading ? <div className="p-5"><CommunityPageSkeleton /></div> : error ? <div className="p-5"><EmptyCommunityState title="" error={error} retry={() => void load()} /></div> : !result?.items.length ? <div className="p-5"><EmptyCommunityState title="No reports found" description="No reports match the current filters." /></div> : <><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-forum-50 text-xs uppercase tracking-wide text-ink-muted"><tr><th className="p-4">Reporter</th><th className="p-4">Reported member</th><th className="p-4">Community</th><th className="p-4">Message</th><th className="p-4">Reason</th><th className="p-4">Date</th><th className="p-4">Status</th><th className="p-4">Assigned</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-paper-border">{result.items.map((report) => <tr key={report.id}><td className="p-4">{report.reporterName}</td><td className="p-4">{report.reportedMemberName ?? '—'}</td><td className="p-4">{report.communityName}</td><td className="max-w-[220px] truncate p-4">{report.reportedMessage?.content ?? '—'}</td><td className="max-w-[220px] truncate p-4">{report.reason}</td><td className="p-4">{formatDate(report.createdAt)}</td><td className="p-4"><CommunityStatusBadge status={report.status} /></td><td className="p-4">{report.assignedAdminName ?? 'Unassigned'}</td><td className="p-4"><div className="flex justify-end gap-1"><Icon title="View report" onClick={() => setDetails(report)}><Eye /></Icon>{report.status === 'OPEN' && <Icon title="Start review" onClick={() => void status(report, 'UNDER_REVIEW')}><RefreshCw /></Icon>}<Icon title="Moderation action" onClick={() => setAction({ report })}><Gavel /></Icon></div></td></tr>)}</tbody></table></div><CommunityPagination meta={result.pagination} onPage={setPage} /></>}</section>{details && <CommunityReportDetailsDrawer report={details} close={() => setDetails(null)} />}{action && <ModerationActionModal initialAction={action.initial} busy={busy} close={() => setAction(null)} submit={(kind, notes) => void moderate(kind, notes)} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}</div>;
}
function Icon({ title, children, onClick }: { title: string; children: React.ReactNode; onClick: () => void }) { return <button type="button" title={title} aria-label={title} onClick={onClick} className="rounded-md p-2 text-forum-700 hover:bg-forum-50 [&>svg]:h-4 [&>svg]:w-4">{children}</button>; }
