import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Lock, LockOpen, MessageSquare, Search } from 'lucide-react';
import Button from '../../../components/common/Button';
import ChatComposer from '../../../components/community/ChatComposer';
import ChatMessageItem from '../../../components/community/ChatMessageItem';
import ConfirmationDialog from '../../../components/community/ConfirmationDialog';
import { CommunityToast, PageHeading, controlClass, formatDate, panelClass } from '../../../components/community/AdminCommunityUi';
import { SAMPLE_ADMIN, communityAdminData } from '../../../data/communityAdminData';
import type { CommunityConversation, CommunityMessage } from '../../../types/community';

type MobilePanel = 'communities' | 'conversations' | 'messages';
export default function AdminCommunityChatsPage() {
  /* Sample-data page: conversations and threads come from the local dataset and mutations stay in memory. Swap for communityAdminService calls once /admin/community/conversations exists. */
  const [conversations, setConversations] = useState<CommunityConversation[]>(communityAdminData.conversations); const [threads, setThreads] = useState<Record<string, CommunityMessage[]>>(() => communityAdminData.messages); const [communityId, setCommunityId] = useState(''); const [conversationId, setConversationId] = useState(''); const [communitySearch, setCommunitySearch] = useState(''); const [conversationSearch, setConversationSearch] = useState(''); const [replyTo, setReplyTo] = useState<CommunityMessage | null>(null); const [deleting, setDeleting] = useState<CommunityMessage | null>(null); const [panel, setPanel] = useState<MobilePanel>('communities'); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null); const scrollRef = useRef<HTMLDivElement>(null); const nearBottom = useRef(true);
  const messages = useMemo(() => conversationId ? threads[conversationId] ?? [] : [], [threads, conversationId]);
  useEffect(() => { if (nearBottom.current) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages]);
  const communities = useMemo(() => Array.from(new Map(conversations.map((item) => [item.communityId, { id: item.communityId, name: item.communityName, unread: 0 }])).values()).map((community) => ({ ...community, unread: conversations.filter((item) => item.communityId === community.id).reduce((sum, item) => sum + item.unreadCount, 0) })).filter((item) => item.name.toLowerCase().includes(communitySearch.toLowerCase())), [communitySearch, conversations]);
  const visibleConversations = conversations.filter((item) => item.communityId === communityId && item.title.toLowerCase().includes(conversationSearch.toLowerCase())); const selected = conversations.find((item) => item.id === conversationId) ?? null;
  const notify = (message: string) => { setToast({ message }); window.setTimeout(() => setToast(null), 3500); };
  const patchMessage = (message: CommunityMessage, patch: { isPinned?: boolean; isHidden?: boolean; isRead?: boolean }) => setThreads((prev) => ({ ...prev, [message.conversationId]: (prev[message.conversationId] ?? []).map((item) => item.id === message.id ? { ...item, ...patch } : item) }));
  const send = async (content: string, files: File[]) => { if (!selected) return false; const created: CommunityMessage = { id: `msg-new-${Date.now()}`, conversationId: selected.id, senderId: SAMPLE_ADMIN.id, senderName: SAMPLE_ADMIN.name, senderRole: 'ADMIN', content, replyTo: replyTo ?? null, attachments: files.map((file) => ({ id: `att-${file.name}-${file.size}`, fileName: file.name, fileUrl: URL.createObjectURL(file), fileType: file.type, fileSize: file.size })), isPinned: false, isHidden: false, isDeleted: false, isRead: true, createdAt: new Date().toISOString() }; setThreads((prev) => ({ ...prev, [selected.id]: [...(prev[selected.id] ?? []), created] })); setConversations((prev) => prev.map((item) => item.id === selected.id ? { ...item, lastMessage: created, messageCount: item.messageCount + 1, updatedAt: created.createdAt } : item)); setReplyTo(null); notify('Message sent.'); return true; };
  const toggleLock = () => { if (!selected) return; const locked = !selected.isLocked; setConversations((prev) => prev.map((item) => item.id === selected.id ? { ...item, isLocked: locked } : item)); notify(locked ? 'Conversation locked.' : 'Conversation unlocked.'); };
  const deleteMessage = () => { if (!deleting) return; setThreads((prev) => ({ ...prev, [deleting.conversationId]: (prev[deleting.conversationId] ?? []).map((item) => item.id === deleting.id ? { ...item, isDeleted: true } : item) })); notify('Message deleted.'); setDeleting(null); };
  return <div className="space-y-6"><PageHeading title="Community Chats" description="Monitor conversations, respond as an administrator, and moderate messages." /><div className={`${panelClass} grid min-h-[650px] overflow-hidden lg:grid-cols-[240px_300px_minmax(0,1fr)]`}>
    <aside className={`${panel !== 'communities' ? 'hidden lg:block' : ''} border-r border-paper-border`}><PanelHeader title="Communities" query={communitySearch} setQuery={setCommunitySearch} />{!communities.length ? <Empty text="No communities" /> : <div className="p-2">{communities.map((community) => <button type="button" key={community.id} onClick={() => { setCommunityId(community.id); setConversationId(''); setPanel('conversations'); }} className={`mb-1 flex w-full items-center justify-between rounded-lg p-3 text-left text-sm ${communityId === community.id ? 'bg-forum-700 text-white' : 'text-forum-900 hover:bg-forum-50'}`}><span className="truncate">{community.name}</span>{community.unread > 0 && <span className="rounded-full bg-brass-500 px-2 py-0.5 text-xs text-white">{community.unread}</span>}</button>)}</div>}</aside>
    <aside className={`${panel !== 'conversations' ? 'hidden lg:block' : ''} border-r border-paper-border`}><div className="lg:hidden"><Back onClick={() => setPanel('communities')} /></div><PanelHeader title="Conversations" query={conversationSearch} setQuery={setConversationSearch} />{!communityId ? <Empty text="Select a community" /> : !visibleConversations.length ? <Empty text="No conversations" /> : <div className="p-2">{visibleConversations.map((conversation) => <button type="button" key={conversation.id} onClick={() => { setConversationId(conversation.id); setPanel('messages'); }} className={`mb-1 w-full rounded-lg p-3 text-left ${conversationId === conversation.id ? 'bg-forum-50 ring-1 ring-forum-200' : 'hover:bg-forum-50'}`}><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-sm font-medium text-forum-900">{conversation.title}</span>{conversation.isLocked && <Lock className="h-3.5 w-3.5 text-ink-subtle" />}{conversation.unreadCount > 0 && <span className="rounded-full bg-brass-500 px-1.5 text-xs text-white">{conversation.unreadCount}</span>}</div><p className="mt-1 truncate text-xs text-ink-muted">{conversation.lastMessage?.content ?? 'No messages yet'}</p><p className="mt-1 text-[11px] text-ink-subtle">{conversation.messageCount} messages · {formatDate(conversation.updatedAt)}</p></button>)}</div>}</aside>
    <section className={`${panel !== 'messages' ? 'hidden lg:flex' : 'flex'} min-h-0 flex-col`}>{!selected ? <div className="flex flex-1 items-center justify-center text-center text-sm text-ink-muted"><div><MessageSquare className="mx-auto mb-2 h-8 w-8" />Select a conversation</div></div> : <><header className="flex items-center justify-between gap-3 border-b border-paper-border p-3"><div className="flex min-w-0 items-center gap-2"><div className="lg:hidden"><Back onClick={() => setPanel('conversations')} /></div><div className="min-w-0"><h2 className="truncate font-semibold text-forum-900">{selected.title}</h2><p className="truncate text-xs text-ink-muted">{selected.communityName}</p></div></div><Button size="sm" variant="outline" onClick={toggleLock}>{selected.isLocked ? <LockOpen className="h-4 w-4" /> : <Lock className="h-4 w-4" />}{selected.isLocked ? 'Unlock' : 'Lock'}</Button></header><div ref={scrollRef} onScroll={(e) => { const el = e.currentTarget; nearBottom.current = el.scrollHeight - el.scrollTop - el.clientHeight < 120; }} className="flex-1 space-y-3 overflow-y-auto bg-forum-50/30 p-3 sm:p-4">{!messages.length ? <Empty text="No messages yet" /> : messages.map((message) => <ChatMessageItem key={message.id} message={message} disabled={false} onReply={() => setReplyTo(message)} onPatch={(patch) => patchMessage(message, patch)} onDelete={() => setDeleting(message)} />)}</div><ChatComposer locked={selected.isLocked} busy={false} replyTo={replyTo} cancelReply={() => setReplyTo(null)} send={send} /></>}</section>
  </div>{deleting && <ConfirmationDialog title="Delete message?" description="The message will be deleted from this conversation." confirmLabel="Delete" busy={false} onClose={() => setDeleting(null)} onConfirm={deleteMessage} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}</div>;
}
function PanelHeader({ title, query, setQuery }: { title: string; query: string; setQuery: (value: string) => void }) { return <header className="border-b border-paper-border p-3"><h2 className="font-semibold text-forum-900">{title}</h2><label className="relative mt-2 block"><span className="sr-only">Search {title}</span><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-ink-subtle" /><input value={query} onChange={(e) => setQuery(e.target.value)} className={`${controlClass} w-full py-2 pl-8 text-xs`} placeholder={`Search ${title.toLowerCase()}`} /></label></header>; }
function Empty({ text }: { text: string }) { return <p className="p-8 text-center text-sm text-ink-muted">{text}</p>; }
function Back({ onClick }: { onClick: () => void }) { return <button type="button" title="Back" aria-label="Back" onClick={onClick} className="rounded-md p-2 text-forum-700 hover:bg-forum-50"><ArrowLeft className="h-4 w-4" /></button>; }
