import { communityChanged, useCommunityResource } from '../../../hooks/useCommunityResource';
import { useEffect, useState } from 'react';
import { Archive, Eye, Pencil, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { normalizeError } from '../../../api/client';
import Button from '../../../components/common/Button';
import CommunityAvatar from '../../../components/community/CommunityAvatar';
import CommunityDeleteDialog from '../../../components/community/CommunityDeleteDialog';
import CommunityDetailsDrawer from '../../../components/community/CommunityDetailsDrawer';
import CommunityFormModal from '../../../components/community/CommunityFormModal';
import CommunityPageSkeleton from '../../../components/community/CommunityPageSkeleton';
import CommunityStatusBadge from '../../../components/community/CommunityStatusBadge';
import EmptyCommunityState from '../../../components/community/EmptyCommunityState';
import { Drawer, CommunityPagination, CommunityToast, PageHeading, controlClass, formatShortDate, panelClass } from '../../../components/community/AdminCommunityUi';
import { useDebouncedValue } from '../../../hooks/useDebouncedValue';
import { communityAdminService } from '../../../services/communityAdminService';
import type { Community, CommunityPayload, CommunityStatus } from '../../../types/community';

type ConfirmAction = { community: Community; action: 'delete' | 'archive' };
export default function AdminCommunitiesPage() {
  const [query, setQuery] = useState(''); const search = useDebouncedValue(query);
  const [filters, setFilters] = useState({ status: '', visibility: '', category: '', sort: 'createdAt:desc' });
  const [page, setPage] = useState(1); const [serverErrors, setServerErrors] = useState<Record<string, string>>({});
  const [editor, setEditor] = useState<Community | 'new' | null>(null); const [details, setDetails] = useState<Community | null>(null); const [confirm, setConfirm] = useState<ConfirmAction | null>(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const { data: result, loading, error, refresh: load } = useCommunityResource(JSON.stringify(['communities', page, search, filters]), () => communityAdminService.getCommunities({ page, limit: 10, search, ...filters }));
  const optionData = useCommunityResource('admin-options', communityAdminService.getOptions);
  const categories = optionData.data?.categories ?? [];
  const detailData = useCommunityResource(details ? `community-detail:${details.id}` : null, () => communityAdminService.getCommunity(details!.id));
  useEffect(() => { setPage(1); }, [search, filters]);
  const notify = (message: string, isError = false) => { setToast({ message, error: isError }); window.setTimeout(() => setToast(null), 3500); };
  const save = async (payload: CommunityPayload) => { if (busy) return; setServerErrors({}); setBusy(true); try { if (editor === 'new') await communityAdminService.createCommunity(payload); else if (editor) await communityAdminService.updateCommunity(editor.id, payload); notify(editor === 'new' ? 'Community created.' : 'Community updated.'); setEditor(null); communityChanged(); await load(); } catch (failure) { setServerErrors(normalizeError(failure).fieldErrors); notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const status = async (community: Community, next: CommunityStatus) => { setBusy(true); try { await communityAdminService.updateCommunityStatus(community.id, next); notify(`Community ${next.toLowerCase()}.`); setConfirm(null); communityChanged(); await load(); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const remove = async (community: Community) => { setBusy(true); try { await communityAdminService.deleteCommunity(community.id); notify('Community deleted.'); setConfirm(null); communityChanged(); await load(); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const changeFilter = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  return <div className="space-y-6"><PageHeading title="Manage Communities" description="Create, update, archive, and monitor all communities." actions={<><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</Button><Button onClick={() => { setServerErrors({}); setEditor('new'); }}><Plus className="h-4 w-4" />Add Community</Button></>} />
    <div className={`${panelClass} p-4`}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="relative"><span className="sr-only">Search communities</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-ink-subtle" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search communities" className={`${controlClass} w-full pl-9`} /></label><Filter label="Status" value={filters.status} onChange={(v) => changeFilter('status', v)} options={['ACTIVE', 'INACTIVE', 'ARCHIVED']} /><Filter label="Visibility" value={filters.visibility} onChange={(v) => changeFilter('visibility', v)} options={['PUBLIC', 'PRIVATE']} /><Filter label="Category" value={filters.category} onChange={(v) => changeFilter('category', v)} options={categories} /><Filter label="Sort" value={filters.sort} onChange={(v) => changeFilter('sort', v)} options={['createdAt:desc', 'createdAt:asc', 'name:asc', 'memberCount:desc']} /></div></div>
    {(optionData.error || (error && result)) && <p role="alert" className="rounded-lg bg-warning-50 p-3 text-sm text-warning-700">{optionData.error || error}</p>}
    <section className={panelClass}>{loading ? <div className="p-5"><CommunityPageSkeleton /></div> : error && !result ? <div className="p-5"><EmptyCommunityState title="" error={error} retry={() => void load()} /></div> : !result?.items.length ? <div className="p-5"><EmptyCommunityState title="No communities found" description="Try changing the filters or add the first community." /></div> : <><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-forum-50 text-xs uppercase tracking-wide text-ink-muted"><tr><th className="p-4">Community</th><th className="p-4">Category</th><th className="p-4">Visibility</th><th className="p-4">Status</th><th className="p-4">Members</th><th className="p-4">Created</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-paper-border">{result.items.map((community) => <tr key={community.id}><td className="p-4"><div className="flex items-center gap-3"><CommunityAvatar name={community.name} src={community.imageUrl} /><div><p className="font-medium text-forum-900">{community.name}</p><p className="text-xs text-ink-muted">/{community.slug}</p></div></div></td><td className="p-4">{community.category}</td><td className="p-4">{community.visibility}</td><td className="p-4"><CommunityStatusBadge status={community.status} /></td><td className="p-4">{community.memberCount.toLocaleString()}</td><td className="p-4">{formatShortDate(community.createdAt)}</td><td className="p-4"><div className="flex justify-end gap-1"><Action title="View" onClick={() => setDetails(community)}><Eye /></Action><Action title="Edit" onClick={() => { setServerErrors({}); setEditor(community); }}><Pencil /></Action><Action title={community.status === 'ACTIVE' ? 'Deactivate' : 'Activate'} onClick={() => void status(community, community.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE')}><RefreshCw /></Action><Action title="Archive" onClick={() => setConfirm({ community, action: 'archive' })}><Archive /></Action><Action title="Delete" danger onClick={() => setConfirm({ community, action: 'delete' })}><Trash2 /></Action></div></td></tr>)}</tbody></table></div><CommunityPagination meta={result.pagination} onPage={setPage} /></>}</section>
    {editor && <CommunityFormModal community={editor === 'new' ? undefined : editor} busy={busy} onClose={() => setEditor(null)} onSubmit={save} serverErrors={serverErrors} />}{details && (detailData.data ? <CommunityDetailsDrawer community={detailData.data} close={() => setDetails(null)} /> : <Drawer title="Community details" close={() => setDetails(null)}>{detailData.loading ? <CommunityPageSkeleton /> : <EmptyCommunityState title="Details unavailable" error={detailData.error} retry={() => void detailData.refresh()} />}</Drawer>)}{confirm && <CommunityDeleteDialog title={confirm.action === 'delete' ? 'Delete community?' : 'Archive community?'} description={confirm.action === 'delete' ? `Delete ${confirm.community.name}? This cannot be undone.` : `Archive ${confirm.community.name}? Members will no longer be able to use it.`} confirmLabel={confirm.action === 'delete' ? 'Delete' : 'Archive'} busy={busy} onClose={() => setConfirm(null)} onConfirm={() => void (confirm.action === 'delete' ? remove(confirm.community) : status(confirm.community, 'ARCHIVED'))} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}
  </div>;
}
function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className={`${controlClass} w-full`}><option value="">All {label.toLowerCase()}</option>{options.map((option) => <option key={option} value={option}>{option.replace(':', ' ')}</option>)}</select>; }
function Action({ title, children, danger = false, onClick }: { title: string; children: React.ReactElement<{ className?: string }>; danger?: boolean; onClick: () => void }) { return <button type="button" title={title} aria-label={title} onClick={onClick} className={`rounded-md p-2 hover:bg-forum-50 ${danger ? 'text-danger-600' : 'text-forum-700'}`}>{children && <span className="[&>svg]:h-4 [&>svg]:w-4">{children}</span>}</button>; }
