import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Lock, LockOpen, MessageSquare, RefreshCw, Search } from 'lucide-react';
import { normalizeError } from '../../../api/client';
import Button from '../../../components/common/Button';
import ChatComposer from '../../../components/community/ChatComposer';
import ChatMessageItem from '../../../components/community/ChatMessageItem';
import CommunityPageSkeleton from '../../../components/community/CommunityPageSkeleton';
import ConfirmationDialog from '../../../components/community/ConfirmationDialog';
import EmptyCommunityState from '../../../components/community/EmptyCommunityState';
import { CommunityToast, PageHeading, controlClass, formatDate, panelClass } from '../../../components/community/AdminCommunityUi';
import { communityAdminService } from '../../../services/communityAdminService';
import type { CommunityConversation, CommunityMessage, PaginatedCommunityResult } from '../../../types/community';

type MobilePanel = 'communities' | 'conversations' | 'messages';
export default function AdminCommunityChatsPage() {
  const [conversations, setConversations] = useState<CommunityConversation[]>([]); const [messages, setMessages] = useState<CommunityMessage[]>([]); const [communityId, setCommunityId] = useState(''); const [conversationId, setConversationId] = useState(''); const [communitySearch, setCommunitySearch] = useState(''); const [conversationSearch, setConversationSearch] = useState(''); const [loading, setLoading] = useState(true); const [messageLoading, setMessageLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [replyTo, setReplyTo] = useState<CommunityMessage | null>(null); const [deleting, setDeleting] = useState<CommunityMessage | null>(null); const [panel, setPanel] = useState<MobilePanel>('communities'); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null); const scrollRef = useRef<HTMLDivElement>(null); const nearBottom = useRef(true);
  const loadConversations = useCallback(async (silent = false) => { if (!silent) setLoading(true); setError(null); try { const result = await communityAdminService.getConversations({ limit: 100 }); setConversations(result.items); } catch (failure) { setError(normalizeError(failure).message); } finally { if (!silent) setLoading(false); } }, []);
  const loadMessages = useCallback(async (silent = false) => { if (!conversationId) { setMessages([]); return; } if (!silent) setMessageLoading(true); try { const result: PaginatedCommunityResult<CommunityMessage> = await communityAdminService.getConversationMessages(conversationId, { limit: 100 }); setMessages(result.items); } catch (failure) { if (!silent) setError(normalizeError(failure).message); } finally { if (!silent) setMessageLoading(false); } }, [conversationId]);
  useEffect(() => { void loadConversations(); const timer = window.setInterval(() => void loadConversations(true), 15000); return () => window.clearInterval(timer); }, [loadConversations]);
  useEffect(() => { void loadMessages(); const timer = window.setInterval(() => void loadMessages(true), 8000); return () => window.clearInterval(timer); }, [loadMessages]);
  useEffect(() => { if (nearBottom.current) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages]);
  const communities = useMemo(() => Array.from(new Map(conversations.map((item) => [item.communityId, { id: item.communityId, name: item.communityName, unread: 0 }])).values()).map((community) => ({ ...community, unread: conversations.filter((item) => item.communityId === community.id).reduce((sum, item) => sum + item.unreadCount, 0) })).filter((item) => item.name.toLowerCase().includes(communitySearch.toLowerCase())), [communitySearch, conversations]);
  const visibleConversations = conversations.filter((item) => item.communityId === communityId && item.title.toLowerCase().includes(conversationSearch.toLowerCase())); const selected = conversations.find((item) => item.id === conversationId) ?? null;
  const notify = (message: string, isError = false) => { setToast({ message, error: isError }); window.setTimeout(() => setToast(null), 3500); };
  const patchMessage = async (message: CommunityMessage, patch: { isPinned?: boolean; isHidden?: boolean; isRead?: boolean }) => { if (busy) return; setBusy(true); try { await communityAdminService.updateMessage(message.id, patch); await loadMessages(true); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const send = async (content: string, files: File[]) => { if (!selected || busy) return false; setBusy(true); try { await communityAdminService.sendAdminMessage(selected.id, { content, attachments: files, replyToId: replyTo?.id }); setReplyTo(null); await loadMessages(true); await loadConversations(true); return true; } catch (failure) { notify(normalizeError(failure).message, true); return false; } finally { setBusy(false); } };
  const toggleLock = async () => { if (!selected || busy) return; setBusy(true); try { await communityAdminService.updateConversation(selected.id, { isLocked: !selected.isLocked }); await loadConversations(true); notify(selected.isLocked ? 'Conversation unlocked.' : 'Conversation locked.'); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  const deleteMessage = async () => { if (!deleting) return; setBusy(true); try { await communityAdminService.deleteMessage(deleting.id); setDeleting(null); await loadMessages(true); notify('Message deleted.'); } catch (failure) { notify(normalizeError(failure).message, true); } finally { setBusy(false); } };
  return <div className="space-y-6"><PageHeading title="Community Chats" description="Monitor conversations, respond as an administrator, and moderate messages." actions={<Button variant="outline" onClick={() => void loadConversations()}><RefreshCw className="h-4 w-4" />Refresh</Button>} />{error && !conversations.length ? <EmptyCommunityState title="" error={error} retry={() => void loadConversations()} /> : <div className={`${panelClass} grid min-h-[650px] overflow-hidden lg:grid-cols-[240px_300px_minmax(0,1fr)]`}>
    <aside className={`${panel !== 'communities' ? 'hidden lg:block' : ''} border-r border-paper-border`}><PanelHeader title="Communities" query={communitySearch} setQuery={setCommunitySearch} />{loading ? <div className="p-3"><CommunityPageSkeleton rows={4} /></div> : !communities.length ? <Empty text="No communities" /> : <div className="p-2">{communities.map((community) => <button type="button" key={community.id} onClick={() => { setCommunityId(community.id); setConversationId(''); setPanel('conversations'); }} className={`mb-1 flex w-full items-center justify-between rounded-lg p-3 text-left text-sm ${communityId === community.id ? 'bg-forum-700 text-white' : 'text-forum-900 hover:bg-forum-50'}`}><span className="truncate">{community.name}</span>{community.unread > 0 && <span className="rounded-full bg-brass-500 px-2 py-0.5 text-xs text-white">{community.unread}</span>}</button>)}</div>}</aside>
    <aside className={`${panel !== 'conversations' ? 'hidden lg:block' : ''} border-r border-paper-border`}><div className="lg:hidden"><Back onClick={() => setPanel('communities')} /></div><PanelHeader title="Conversations" query={conversationSearch} setQuery={setConversationSearch} />{!communityId ? <Empty text="Select a community" /> : !visibleConversations.length ? <Empty text="No conversations" /> : <div className="p-2">{visibleConversations.map((conversation) => <button type="button" key={conversation.id} onClick={() => { setConversationId(conversation.id); setPanel('messages'); }} className={`mb-1 w-full rounded-lg p-3 text-left ${conversationId === conversation.id ? 'bg-forum-50 ring-1 ring-forum-200' : 'hover:bg-forum-50'}`}><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-sm font-medium text-forum-900">{conversation.title}</span>{conversation.isLocked && <Lock className="h-3.5 w-3.5 text-ink-subtle" />}{conversation.unreadCount > 0 && <span className="rounded-full bg-brass-500 px-1.5 text-xs text-white">{conversation.unreadCount}</span>}</div><p className="mt-1 truncate text-xs text-ink-muted">{conversation.lastMessage?.content ?? 'No messages yet'}</p><p className="mt-1 text-[11px] text-ink-subtle">{conversation.messageCount} messages · {formatDate(conversation.updatedAt)}</p></button>)}</div>}</aside>
    <section className={`${panel !== 'messages' ? 'hidden lg:flex' : 'flex'} min-h-0 flex-col`}>{!selected ? <div className="flex flex-1 items-center justify-center text-center text-sm text-ink-muted"><div><MessageSquare className="mx-auto mb-2 h-8 w-8" />Select a conversation</div></div> : <><header className="flex items-center justify-between gap-3 border-b border-paper-border p-3"><div className="flex min-w-0 items-center gap-2"><div className="lg:hidden"><Back onClick={() => setPanel('conversations')} /></div><div className="min-w-0"><h2 className="truncate font-semibold text-forum-900">{selected.title}</h2><p className="truncate text-xs text-ink-muted">{selected.communityName}</p></div></div><Button size="sm" variant="outline" onClick={() => void toggleLock()} disabled={busy}>{selected.isLocked ? <LockOpen className="h-4 w-4" /> : <Lock className="h-4 w-4" />}{selected.isLocked ? 'Unlock' : 'Lock'}</Button></header><div ref={scrollRef} onScroll={(e) => { const el = e.currentTarget; nearBottom.current = el.scrollHeight - el.scrollTop - el.clientHeight < 120; }} className="flex-1 space-y-3 overflow-y-auto bg-forum-50/30 p-3 sm:p-4">{messageLoading ? <CommunityPageSkeleton /> : !messages.length ? <Empty text="No messages yet" /> : messages.map((message) => <ChatMessageItem key={message.id} message={message} disabled={busy} onReply={() => setReplyTo(message)} onPatch={(patch) => void patchMessage(message, patch)} onDelete={() => setDeleting(message)} />)}</div><ChatComposer locked={selected.isLocked} busy={busy} replyTo={replyTo} cancelReply={() => setReplyTo(null)} send={send} /></>}</section>
  </div>}{deleting && <ConfirmationDialog title="Delete message?" description="The message will be deleted from this conversation." confirmLabel="Delete" busy={busy} onClose={() => setDeleting(null)} onConfirm={() => void deleteMessage()} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}</div>;
}
function PanelHeader({ title, query, setQuery }: { title: string; query: string; setQuery: (value: string) => void }) { return <header className="border-b border-paper-border p-3"><h2 className="font-semibold text-forum-900">{title}</h2><label className="relative mt-2 block"><span className="sr-only">Search {title}</span><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-ink-subtle" /><input value={query} onChange={(e) => setQuery(e.target.value)} className={`${controlClass} w-full py-2 pl-8 text-xs`} placeholder={`Search ${title.toLowerCase()}`} /></label></header>; }
function Empty({ text }: { text: string }) { return <p className="p-8 text-center text-sm text-ink-muted">{text}</p>; }
function Back({ onClick }: { onClick: () => void }) { return <button type="button" title="Back" aria-label="Back" onClick={onClick} className="rounded-md p-2 text-forum-700 hover:bg-forum-50"><ArrowLeft className="h-4 w-4" /></button>; }
