import { useMemo, useState } from 'react';
import { Eye, Gavel, RefreshCw, Search } from 'lucide-react';
import CommunityReportDetailsDrawer from '../../../components/community/CommunityReportDetailsDrawer';
import CommunityStatusBadge from '../../../components/community/CommunityStatusBadge';
import EmptyCommunityState from '../../../components/community/EmptyCommunityState';
import ModerationActionModal from '../../../components/community/ModerationActionModal';
import { CommunityPagination, CommunityToast, PageHeading, controlClass, formatDate, panelClass, samplePage } from '../../../components/community/AdminCommunityUi';
import { SAMPLE_ADMIN, communityAdminData } from '../../../data/communityAdminData';
import type { CommunityReport, ReportStatus } from '../../../types/community';

export default function AdminCommunityModerationPage() {
  /* Sample-data page: reports come from the local dataset and moderation actions stay in memory. Swap for communityAdminService.getReports/updateReport once /admin/community/reports exists. */
  const [reports, setReports] = useState<CommunityReport[]>(communityAdminData.reports); const communities = useMemo(() => communityAdminData.communities.map(({ id, name }) => ({ id, name })).sort((a, b) => a.name.localeCompare(b.name)), []); const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ status: '', communityId: '', dateFrom: '' }); const [page, setPage] = useState(1); const [detailsId, setDetailsId] = useState<string | null>(null); const [actionId, setActionId] = useState<string | null>(null); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const notify = (message: string) => { setToast({ message }); window.setTimeout(() => setToast(null), 3500); };
  const details = reports.find((item) => item.id === detailsId) ?? null; const action = reports.find((item) => item.id === actionId) ?? null;
  const result = useMemo(() => {
    const term = query.trim().toLowerCase();
    const filtered = reports.filter((report) => (!term || [report.reporterName, report.reportedMemberName ?? '', report.reason, report.communityName, report.reportedMessage?.content ?? ''].some((value) => value.toLowerCase().includes(term))) && (!filters.status || report.status === filters.status) && (!filters.communityId || report.communityId === filters.communityId) && (!filters.dateFrom || report.createdAt.slice(0, 10) >= filters.dateFrom));
    return samplePage([...filtered].sort((a, b) => b.createdAt.localeCompare(a.createdAt)), page);
  }, [reports, query, filters, page]);
  const status = (report: CommunityReport, next: ReportStatus, notes?: string) => { setReports((prev) => prev.map((item) => item.id === report.id ? { ...item, status: next, resolutionNotes: notes ?? item.resolutionNotes, assignedAdminName: next === 'UNDER_REVIEW' ? item.assignedAdminName ?? SAMPLE_ADMIN.name : item.assignedAdminName, updatedAt: new Date().toISOString() } : item)); notify(`Report marked ${next.toLowerCase().replace('_', ' ')}.`); setActionId(null); };
  const moderate = (kind: string, notes: string) => { if (!action) return; if (kind === 'RESOLVE_REPORT') { status(action, 'RESOLVED', notes); return; } if (kind === 'DISMISS_REPORT') { status(action, 'DISMISSED', notes); return; } setReports((prev) => prev.map((item) => item.id === action.id ? { ...item, actionHistory: [...(item.actionHistory ?? []), { id: `hist-${Date.now()}`, action: kind.replace(/_/g, ' '), notes, adminName: SAMPLE_ADMIN.name, createdAt: new Date().toISOString() }], updatedAt: new Date().toISOString() } : item)); notify('Moderation action applied.'); setActionId(null); };
  return <div className="space-y-6"><PageHeading title="Reports & Moderation" description="Review reports and take documented action on unsafe content or members." /><div className={`${panelClass} grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4`}><label className="relative"><span className="sr-only">Search reports</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-ink-subtle" /><input className={`${controlClass} w-full pl-9`} value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search reports" /></label><select aria-label="Status" className={controlClass} value={filters.status} onChange={(e) => { setFilters((f) => ({ ...f, status: e.target.value })); setPage(1); }}><option value="">All statuses</option>{['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED'].map((v) => <option key={v}>{v}</option>)}</select><select aria-label="Community" className={controlClass} value={filters.communityId} onChange={(e) => { setFilters((f) => ({ ...f, communityId: e.target.value })); setPage(1); }}><option value="">All communities</option>{communities.map((community) => <option key={community.id} value={community.id}>{community.name}</option>)}</select><input aria-label="Reported since" title="Reported since" type="date" className={controlClass} value={filters.dateFrom} onChange={(e) => { setFilters((f) => ({ ...f, dateFrom: e.target.value })); setPage(1); }} /></div>
    <section className={panelClass}>{!result.items.length ? <div className="p-5"><EmptyCommunityState title="No reports found" description="No reports match the current filters." /></div> : <><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-forum-50 text-xs uppercase tracking-wide text-ink-muted"><tr><th className="p-4">Reporter</th><th className="p-4">Reported member</th><th className="p-4">Community</th><th className="p-4">Message</th><th className="p-4">Reason</th><th className="p-4">Date</th><th className="p-4">Status</th><th className="p-4">Assigned</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-paper-border">{result.items.map((report) => <tr key={report.id}><td className="p-4">{report.reporterName}</td><td className="p-4">{report.reportedMemberName ?? '—'}</td><td className="p-4">{report.communityName}</td><td className="max-w-[220px] truncate p-4">{report.reportedMessage?.content ?? '—'}</td><td className="max-w-[220px] truncate p-4">{report.reason}</td><td className="p-4">{formatDate(report.createdAt)}</td><td className="p-4"><CommunityStatusBadge status={report.status} /></td><td className="p-4">{report.assignedAdminName ?? 'Unassigned'}</td><td className="p-4"><div className="flex justify-end gap-1"><Icon title="View report" onClick={() => setDetailsId(report.id)}><Eye /></Icon>{report.status === 'OPEN' && <Icon title="Start review" onClick={() => status(report, 'UNDER_REVIEW')}><RefreshCw /></Icon>}<Icon title="Moderation action" onClick={() => setActionId(report.id)}><Gavel /></Icon></div></td></tr>)}</tbody></table></div><CommunityPagination meta={result.pagination} onPage={setPage} /></>}</section>{details && <CommunityReportDetailsDrawer report={details} close={() => setDetailsId(null)} />}{action && <ModerationActionModal busy={false} close={() => setActionId(null)} submit={moderate} />}{toast && <CommunityToast {...toast} close={() => setToast(null)} />}</div>;
}
function Icon({ title, children, onClick }: { title: string; children: React.ReactNode; onClick: () => void }) { return <button type="button" title={title} aria-label={title} onClick={onClick} className="rounded-md p-2 text-forum-700 hover:bg-forum-50 [&>svg]:h-4 [&>svg]:w-4">{children}</button>; }
