import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Save, RefreshCw, ChevronRight, Settings, Building2, Users, Calendar, Mail, Clock, Lock, Plug, Wallet, Database } from 'lucide-react';
import { Card, CardHeader, CardContent } from '../../components/common/Card';
import Button from '../../components/common/Button';
import Badge from '../../components/common/Badge';
import { TextInput, TextArea, SelectInput, Checkbox } from '../../components/common/Input';
import { useSettings } from '../../hooks/useSettings';
import { type SettingsSection } from '../../services/settingsService';
import { auditService } from '../../services/auditService';
import { formatConfiguredDate, usePublicSettings } from '../../context/SettingsContext';
const tabs = [
  { key: 'general', label: 'General', hint: 'Organization, contact and formatting', icon: Building2 },
  { key: 'membership', label: 'Membership', hint: 'Applications and credentials', icon: Users },
  { key: 'events', label: 'Events & Calendar', hint: 'New event defaults', icon: Calendar },
  { key: 'communications', label: 'Communications', hint: 'Sender identity and announcements', icon: Mail },
  { key: 'review', label: 'Review & SLA', hint: 'Calendar-day queue thresholds', icon: Clock },
  { key: 'security', label: 'Security & Privacy', hint: 'Authentication and privacy', icon: Lock },
  { key: 'integrations', label: 'Integrations & API', hint: 'Deployment capabilities', icon: Plug },
  { key: 'billing', label: 'Billing & Finance', hint: 'Payments and invoicing', icon: Wallet },
  { key: 'backup', label: 'Backup & Audit', hint: 'Audit records and exports', icon: Database },
] as const;
type Field = { key: string; label: string; type?: 'number' | 'email' | 'textarea' | 'checkbox'; options?: string[]; hint?: string };
type Group = { title: string; fields?: Field[]; unavailable?: string[]; reason?: string };
const groups: Record<SettingsSection, Group[]> = {
  general: [
    { title: 'Organization Identity', fields: [{ key: 'fullName', label: 'Organization full name' }, { key: 'shortName', label: 'Short name / acronym' }, { key: 'legalName', label: 'Legal entity name' }, { key: 'registrationNumber', label: 'Registration number' }, { key: 'address', label: 'Office address', type: 'textarea' }, { key: 'contactEmail', label: 'Contact email', type: 'email' }, { key: 'contactPhone', label: 'Contact phone' }] },
    { title: 'Regional Defaults & Links', fields: [{ key: 'locale', label: 'Formatting locale', options: ['en-GB', 'en-US', 'es', 'fr', 'de', 'ja', 'zh-CN', 'hi', 'ar'], hint: 'Controls date formatting, not interface translation.' }, { key: 'timezone', label: 'Default timezone', hint: 'Canonical IANA name, for example Asia/Kolkata. New events inherit this default.' }, { key: 'dateFormat', label: 'Date format', options: ['long', 'MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] }, { key: 'homepageUrl', label: 'Organization website' }, { key: 'communityUrl', label: 'Community URL' }] },
    { title: 'Public Notice', fields: [{ key: 'maintenance', label: 'Display a maintenance notice on public pages', type: 'checkbox', hint: 'Sign-in and all workflows remain available.' }, { key: 'maintenanceMessage', label: 'Notice message', type: 'textarea' }] },
  ],
  membership: [{ title: 'Application & Credential Review SLA', fields: [{ key: 'pendingDays', label: 'Pending → start review (calendar days)', type: 'number' }, { key: 'reviewDays', label: 'Under review → decision (calendar days)', type: 'number' }] }, { title: 'Fees, References & Archival', unavailable: ['Application fee', 'Annual dues', 'Financial hardship waivers', 'Required referrals', 'Reference letters', 'Automatic archival after rejection'], reason: 'These workflows are not implemented.' }],
  events: [{ title: 'Event Defaults & RSVP', fields: [{ key: 'capacity', label: 'Default capacity (0 = unlimited)', type: 'number' }, { key: 'reminderDays', label: 'Default reminder (days before event)', options: ['0', '1', '3', '7'], hint: 'One reminder per event. New-event defaults do not change saved events.' }, { key: 'registrationRequired', label: 'Enable registration by default on new events', type: 'checkbox' }] }, { title: 'Recording, Privacy & Feeds', unavailable: ['Automatic video recording and transcription', 'Chatham House enforcement', 'Weekly event digest', 'Public iCal feed'], reason: 'These capabilities are not implemented.' }],
  communications: [{ title: 'Sender Identity & Default Signature', fields: [{ key: 'senderName', label: 'From name' }, { key: 'replyTo', label: 'Reply-To', type: 'email' }, { key: 'signature', label: 'Default email signature', type: 'textarea', hint: 'Plain text appended to supported outgoing emails. Leave blank to omit.' }] }, { title: 'Announcements', fields: [{ key: 'announcementSignoff', label: 'Enable SAB preview and sign-off by default for new drafts', type: 'checkbox', hint: 'Existing drafts remain unchanged. Administrators can override this in each announcement.' }] }, { title: 'Newsletters & Support Acknowledgements', unavailable: ['Weekly community newsletter', 'Weekly member digest', 'Newsletter PDF attachment', 'Automatic support acknowledgement template'], reason: 'Automated delivery for these categories is not implemented.' }],
  review: [{ title: 'Review SLAs (Calendar Days)', fields: [{ key: 'publicationDays', label: 'Publications: review threshold (days)', type: 'number' }, { key: 'projectDays', label: 'Project proposals: review threshold (days)', type: 'number' }, { key: 'supportDays', label: 'Support: open-request age threshold (days)', type: 'number', hint: 'Measures age since creation, not first-response time.' }] }, { title: 'Review Automation', unavailable: ['Auto-escalate publications', 'Auto-escalate projects', 'Double-blind review', 'Conflict-of-interest checks', 'Reviewer workload limits'], reason: 'No automated review assignment or enforcement is implemented.' }, { title: 'Delegate Reviewers by Track', unavailable: ['Add delegate', 'Remove delegate'], reason: 'Reviewer delegation is unavailable. No delegates are configured.' }],
  security: [{ title: 'Privacy Contact', fields: [{ key: 'privacyEmail', label: 'DPO / privacy contact email', type: 'email', hint: 'Displayed in public contact information.' }] }, { title: 'Unavailable Authentication & Retention Controls', unavailable: ['Mandatory MFA and grace period', 'SSO enforcement', 'Password expiry', 'Password history', 'Session IP pinning', 'Idle-session timeout', 'Automatic user-data deletion', 'Automatic credential deletion'], reason: 'These policies are not implemented. Audit retention remains indefinite.' }],
  integrations: [{ title: 'Single Sign-On & Provisioning', unavailable: ['SAML', 'OIDC', 'SCIM'], reason: 'Single sign-on and provisioning are unavailable.' }, { title: 'Webhooks & API Clients', unavailable: ['Add webhook', 'Create API client', 'Rotate client credentials', 'Revoke API client'], reason: 'There is no API-client or webhook management system.' }],
  billing: [{ title: 'Billing & Payment Processing', unavailable: ['Currency', 'Tax / VAT registration', 'Payment processor', 'Invoice prefix', 'Payment terms', 'Late fees'], reason: 'Payment and accounting workflows are unavailable.' }, { title: 'Funding Budget', unavailable: ['Annual award budget', 'Fiscal year', 'Committed', 'Disbursed', 'Remaining'], reason: 'No financial ledger or budget workflow is implemented.' }],
  backup: [{ title: 'Backup Scheduling & Recovery', unavailable: ['Daily incremental backup', 'Weekly full backup', 'Backup time', 'Online retention', 'Cold archive retention', 'Off-site replication', 'Key rotation', 'Recovery drills', 'Trigger on-demand backup'], reason: 'Backups are managed outside this application; their status is unavailable here.' }, { title: 'Integrity & Export Formats', unavailable: ['Run integrity check', 'Signed PDF export', 'JSON export'], reason: 'Hash-chain verification and signed exports are not implemented. CSV audit export is available above.' }],
};
export default function AdminSettingsPage() {
  const [tab, setTab] = useState<SettingsSection>('general');
  const state = useSettings(), publicSettings = usePublicSettings();
  const { data, draft } = state;
  const [exporting, setExporting] = useState(false), exportRequest = useRef<AbortController | null>(null);
  useEffect(() => () => exportRequest.current?.abort(), []);
  useEffect(() => { if (!data) { exportRequest.current?.abort(); setExporting(false); } }, [data]);
  if (!data || !draft) return <Card><CardContent className="p-6"><p role={state.error ? 'alert' : 'status'}>{state.error || 'Loading administration settings…'}</p>{!state.denied && !state.loading && <Button onClick={() => void state.load(false)}>Retry</Button>}</CardContent></Card>;
  const meta = tabs.find(t => t.key === tab)!;
  const editable = data.sections[tab].editable;
  const values = draft[tab] as Record<string, string | number | boolean>;
  const set = (key: string, value: string | number | boolean) => state.setDraft(d => d ? { ...d, [tab]: { ...d[tab], [key]: value } } : d);
  const buttons = <><Button variant="outline" size="sm" disabled={!editable || state.busy || !!state.conflict} onClick={() => state.setDraft(d => d ? { ...d, [tab]: structuredClone(data.defaults[tab]) } : d)}><RefreshCw className="h-3.5 w-3.5" /> Reset to defaults</Button><Button size="sm" disabled={!editable || state.busy || !!state.conflict} onClick={() => void state.save(tab)}><Save className="h-3.5 w-3.5" />{state.busy ? 'Saving…' : `Save ${meta.label}`}</Button></>;
  const exportCsv = async () => {
    if (exportRequest.current) return; const r = new AbortController(); exportRequest.current = r; setExporting(true);
    try { const blob = await auditService.export({ search: '', actorRole: '', module: '', action: '', severity: '', from: '', to: '', sort: 'newest' }, r.signal); if (r.signal.aborted) return; const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = 'audit-log-all-time.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); void state.load(); }
    catch(e) { if (!r.signal.aborted) state.fail(e); } finally { if (exportRequest.current === r) { exportRequest.current = null; setExporting(false); } }
  };
  return <div className="space-y-6">
    <div className="flex flex-col xl:flex-row xl:items-start justify-between gap-5"><div className="flex-1 max-w-3xl"><Link to="/admin" className="inline-flex items-center gap-1 text-xs text-forum-700"><ArrowLeft className="h-3 w-3" />Admin home</Link><h1 className="font-display text-2xl sm:text-3xl font-semibold text-forum-900 mt-2">{publicSettings?.shortName || 'IFSMHP'} Administration Settings</h1><p className="mt-1.5 text-ink-muted">Platform-wide configuration for the Central Research Office. Saved changes are recorded in the audit log.</p></div><div className="flex flex-wrap items-center gap-2">{buttons}</div></div>
    {state.error && <div role="alert" className="rounded-lg border border-danger-200 p-4 text-danger-700">{state.error}{!state.conflict && <Button variant="ghost" onClick={() => void state.load()}>Refresh</Button>}</div>}
    {state.success && <p role="status" className="text-success-700">{state.success}</p>}
    {state.conflict && <Card><CardContent className="p-4 space-y-3"><p>Your draft is preserved. Review the current saved values before applying it.</p>{!state.reviewed ? <Button onClick={() => void state.load(true, true)} disabled={state.loading}>Load latest values</Button> : <><pre className="text-xs overflow-auto max-h-64">{JSON.stringify(data.values[state.conflict], null, 2)}</pre><Button onClick={state.confirmReview}>I have reviewed the latest values</Button></>}</CardContent></Card>}
    <div className="grid gap-6 lg:grid-cols-5"><Card className="lg:col-span-1 lg:self-start lg:sticky lg:top-4"><CardHeader><h3 className="font-display text-lg font-semibold text-forum-900 flex items-center gap-2"><Settings className="h-5 w-5" />Settings</h3></CardHeader><CardContent className="pt-0 space-y-1">{tabs.map(t => <button key={t.key} aria-current={tab === t.key ? 'page' : undefined} onClick={() => setTab(t.key)} className={`w-full flex items-start gap-2 p-2.5 rounded-lg text-left ${tab === t.key ? 'bg-forum-50 ring-1 ring-forum-100' : 'hover:bg-forum-50/40'}`}><div className={`h-8 w-8 shrink-0 rounded-md flex items-center justify-center ${tab === t.key ? 'bg-forum-600 text-white' : 'bg-forum-50 text-forum-700'}`}><t.icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium break-words">{t.label}</p><p className="text-[10px] text-ink-subtle">{t.hint}</p></div><ChevronRight className="h-4 w-4 shrink-0" /></button>)}</CardContent></Card>
    <div className="lg:col-span-4 space-y-5"><Card><CardHeader><h2 className="font-display text-xl font-semibold text-forum-900">{meta.label} Settings</h2><p className="text-xs text-ink-subtle mt-1">{data.sections[tab].updatedAt ? `Last saved ${formatConfiguredDate(data.sections[tab].updatedAt!, publicSettings)}. ` : 'No administrator changes recorded.'} {editable ? 'Reset changes the draft; save to apply it.' : 'This section has no editable settings.'}</p></CardHeader></Card>
    {tab === 'membership' && <Facts title="Member Identity & Credentials" rows={{ 'Member ID issuance': 'Automatic on approval', 'Member ID format': 'IFSMHP-YYYY-NNNNNN', 'Required documents': 'CV and credential document' }} />}
    {tab === 'communications' && <Facts title="Mail Delivery" rows={{ 'SMTP': data.deployment.mailConfigured ? 'Configured' : 'Unavailable — SMTP is not configured', 'From email (deployment-controlled)': data.deployment.senderAddress || 'Not configured' }} />}
    {tab === 'security' && <Facts title="Authentication & Retention" rows={{ 'New administrator password': 'At least 14 characters; at most 72 UTF-8 bytes', 'Access token lifetime': `${data.deployment.accessMinutes} minutes`, 'Refresh session lifetime': `${data.deployment.refreshDays} days (30 days with Remember me)`, 'Idle timeout': 'Not enforced', 'Audit retention': data.deployment.retention, 'Credential deletion schedule': 'No automatic deletion policy' }} />}
    {tab === 'integrations' && <Facts title="Configured Services" rows={{ 'Email transport': data.deployment.mailConfigured ? 'SMTP configured' : 'SMTP unavailable', 'File storage': data.deployment.storage, 'Video / events': 'External links configured per event' }} />}
    {tab === 'backup' && <Card><CardHeader><h3 className="font-display text-lg font-semibold">Audit Records</h3></CardHeader><CardContent className="pt-0 space-y-4"><p className="font-display text-3xl">{data.deployment.auditCount.toLocaleString(publicSettings?.locale)}</p><p>Recorded audit events · Retention: {data.deployment.retention}</p><Button onClick={() => void exportCsv()} disabled={exporting}>{exporting ? 'Exporting…' : 'Export audit (all time, CSV)'}</Button></CardContent></Card>}
    {groups[tab].map(group => <Card key={group.title}><CardHeader><h3 className="font-display text-lg font-semibold text-forum-900">{group.title}</h3></CardHeader><CardContent className="pt-0 space-y-4">{group.fields && <fieldset disabled={state.busy} className="grid gap-4 sm:grid-cols-2">{group.fields.map(f => {
      const error = state.fields[f.key], common = { label: f.label, error, hint: f.hint };
      if (f.type === 'checkbox') return <div key={f.key} className="sm:col-span-2"><Checkbox id={`setting-${f.key}`} name={f.key} label={f.label} checked={Boolean(values[f.key])} onChange={e => set(f.key, e.target.checked)} /><p className="text-xs text-ink-subtle">{error || f.hint}</p></div>;
      if (f.type === 'textarea') return <TextArea key={f.key} {...common} className="sm:col-span-2" value={String(values[f.key])} onChange={e => set(f.key, e.target.value)} />;
      if (f.options) return <SelectInput key={f.key} {...common} value={String(values[f.key])} onChange={e => set(f.key, f.key === 'reminderDays' ? Number(e.target.value) : e.target.value)}>{f.options.map(o => <option key={o}>{o}</option>)}</SelectInput>;
      return <TextInput key={f.key} {...common} type={f.type ?? 'text'} value={String(values[f.key])} onChange={e => set(f.key, f.type === 'number' ? e.target.value === '' ? '' : Number(e.target.value) : e.target.value)} />;
    })}</fieldset>}{group.unavailable && <><p className="text-sm text-ink-muted">{group.reason}</p><div className="grid gap-3 sm:grid-cols-2">{group.unavailable.map(label => <div key={label} className="flex items-center justify-between gap-2 p-3 rounded-lg border border-paper-border"><span className="text-sm text-ink-muted">{label}</span><Badge variant="default">Unavailable</Badge></div>)}</div></>}</CardContent></Card>)}
    <div className="flex flex-wrap gap-2 justify-end">{buttons}</div><p className="text-xs text-ink-subtle">Supported settings take effect after saving. <Link className="text-forum-700 underline" to="/admin/audit-log?module=SETTINGS">View configuration audit trail</Link></p></div></div>
  </div>;
}
function Facts({ title, rows }: { title: string; rows: Record<string, string> }) { return <Card><CardHeader><h3 className="font-display text-lg font-semibold text-forum-900">{title}</h3></CardHeader><CardContent className="pt-0"><dl className="divide-y divide-paper-border">{Object.entries(rows).map(([name, value]) => <div className="grid gap-2 sm:grid-cols-2 py-3" key={name}><dt className="text-sm text-ink-muted">{name}</dt><dd className="text-sm font-medium break-words">{value}</dd></div>)}</dl></CardContent></Card>; }
